import type { QuestionSnapshot } from './types'

const choice = (code: string, category: string, text: string, scope: 'individual' | 'family', options: string[], sensitivity: QuestionSnapshot['sensitivity'] = 'pastoral', dependsOn?: QuestionSnapshot['dependsOn']): QuestionSnapshot => ({ code, version: 1, category, text, scope, responseType: 'choice', options, sensitivity, ...(dependsOn ? { dependsOn } : {}) })
const text = (code: string, category: string, question: string, scope: 'individual' | 'family', sensitivity: QuestionSnapshot['sensitivity'] = 'pastoral'): QuestionSnapshot => ({ code, version: 1, category, text: question, scope, responseType: 'text', options: [], sensitivity })
const textoCondicional = (code: string, category: string, question: string, dependsOn: QuestionSnapshot['dependsOn']): QuestionSnapshot => ({ ...text(code, category, question, 'individual'), ...(dependsOn ? { dependsOn } : {}) })
const number = (code: string, category: string, question: string, unit?: string, scaleMax?: number, dependsOn?: QuestionSnapshot['dependsOn']): QuestionSnapshot => ({ code, version: 1, category, text: question, scope: 'individual', responseType: 'number', options: [], sensitivity: 'pastoral', ...(unit ? { unit } : {}), ...(scaleMax ? { scaleMax } : {}), ...(dependsOn ? { dependsOn } : {}) })

export const OFFICIAL_QUESTIONNAIRE_VERSION = '2026.1'
export const OFFICIAL_QUESTIONS: QuestionSnapshot[] = [
  choice('COM-01', 'Comunhão', 'Você estudou a Bíblia hoje?', 'individual', ['Sim', 'Não', 'Prefere não responder']),
  number('COM-02', 'Comunhão', 'Quanto tempo aproximadamente dedicou ao estudo da Bíblia hoje?', 'minutos', undefined, { code: 'COM-01', answers: ['Sim'] }), number('COM-03', 'Comunhão', 'Em quantos dias dos últimos 7 dias você estudou a Bíblia?', 'dias', 7),
  choice('COM-04', 'Comunhão', 'Você orou hoje?', 'individual', ['Sim', 'Não', 'Prefere não responder']), number('COM-05', 'Comunhão', 'Quanto tempo aproximadamente dedicou à oração hoje?', 'minutos', undefined, { code: 'COM-04', answers: ['Sim'] }), number('COM-06', 'Comunhão', 'Em quantos dias dos últimos 7 dias você teve oração pessoal?', 'dias', 7),
  choice('COM-07', 'Comunhão', 'Você estudou a Lição da Escola Sabatina nesta semana?', 'individual', ['0', '1', '2', '3', '4', '5', '6', '7', 'Não possui']), text('COM-08', 'Comunhão', 'O que mais tem ajudado sua comunhão com Deus?', 'individual'), text('COM-09', 'Comunhão', 'Existe alguma dificuldade que tem atrapalhado sua vida devocional?', 'individual'), text('COM-10', 'Comunhão', 'Há algum tema bíblico sobre o qual gostaria de conversar?', 'individual'),
  choice('FAM-01', 'Família', 'A família realiza culto familiar?', 'family', ['Sim', 'Não', 'Às vezes']), choice('FAM-02', 'Família', 'Com que frequência costuma realizar?', 'family', ['Diária', 'Semanal', 'Ocasional'], 'pastoral', { code: 'FAM-01', answers: ['Sim', 'Às vezes'] }), text('FAM-03', 'Família', 'Existe alguma dificuldade para realizar o culto familiar?', 'family'), choice('FAM-04', 'Família', 'Gostariam de receber orientação ou material para o culto familiar?', 'family', ['Sim', 'Não']),
  choice('REL-01', 'Relacionamento', 'Você tem participado dos cultos?', 'individual', ['Regularmente', 'Às vezes', 'Não', 'Prefere não responder']), choice('REL-02', 'Relacionamento', 'Você participa da Escola Sabatina?', 'individual', ['Regularmente', 'Às vezes', 'Não']), choice('REL-03', 'Relacionamento', 'Você participa de uma Unidade de Ação?', 'individual', ['Sim', 'Não', 'Não sabe']), choice('REL-04', 'Relacionamento', 'Você participa de um Pequeno Grupo?', 'individual', ['Sim', 'Não', 'Gostaria']), choice('REL-05', 'Relacionamento', 'Você se sente acolhido e integrado à igreja?', 'individual', ['Sim', 'Parcialmente', 'Não', 'Prefere não responder']), choice('REL-06', 'Relacionamento', 'Possui alguém de confiança na igreja com quem pode conversar?', 'individual', ['Sim', 'Não', 'Prefere não responder']),
  { code: 'REL-07', version: 1, category: 'Relacionamento', text: 'O que você mais gosta de fazer na igreja?', scope: 'individual', responseType: 'multiple', options: ['Recepção', 'Oração', 'Louvor', 'Ensino', 'Visitação', 'Ação social', 'Evangelismo', 'Comunicação', 'Crianças', 'Adolescentes', 'Jovens', 'Liderança', 'Organização', 'Manutenção', 'Culinária', 'Outro'], sensitivity: 'pastoral' }, choice('REL-08', 'Relacionamento', 'Existe alguma situação na igreja que gostaria de conversar em particular?', 'individual', ['Sim', 'Não', 'Prefere não responder']),
  choice('MIS-01', 'Missão', 'Você está dando estudo bíblico para alguém?', 'individual', ['Sim', 'Não']), number('MIS-02', 'Missão', 'Para quantas pessoas está dando estudo?', 'pessoas', undefined, { code: 'MIS-01', answers: ['Sim'] }), choice('MIS-03', 'Missão', 'Participa de uma dupla missionária ativa?', 'individual', ['Sim', 'Não', 'Gostaria']), choice('MIS-04', 'Missão', 'Compartilhou sua fé ou convidou alguém recentemente?', 'individual', ['Sim', 'Não', 'Prefere não responder']), text('MIS-05', 'Missão', 'Há alguém por quem você está orando para conhecer a Cristo?', 'individual'), choice('MIS-06', 'Missão', 'Gostaria de aprender a dar estudos bíblicos?', 'individual', ['Sim', 'Não'], 'pastoral', { code: 'MIS-01', answers: ['Não'] }), textoCondicional('MIS-07', 'Missão', 'Conhece alguém que gostaria de estudar a Bíblia ou receber uma visita?', { code: 'MIS-01', answers: ['Não'] }),
  choice('SAU-01', 'Saúde', 'Tem conseguido dormir aproximadamente 8 horas por noite?', 'individual', ['Sim', 'Às vezes', 'Não'], 'health_general'), choice('SAU-02', 'Saúde', 'Tem bebido aproximadamente 2 litros de água por dia?', 'individual', ['Sim', 'Às vezes', 'Não', 'Não se aplica'], 'health_general'), choice('SAU-03', 'Saúde', 'Como está sua alimentação no dia a dia?', 'individual', ['Boa', 'Razoável', 'Precisa melhorar', 'Prefere não responder'], 'health_general'), choice('SAU-04', 'Saúde', 'Tem praticado alguma atividade física regularmente?', 'individual', ['Sim', 'Às vezes', 'Não'], 'health_general'), choice('SAU-05', 'Saúde', 'Tem tido contato adequado com luz solar e ar puro?', 'individual', ['Sim', 'Às vezes', 'Não'], 'health_general'), choice('SAU-06', 'Saúde', 'Tem conseguido equilibrar trabalho, descanso e hábitos?', 'individual', ['Sim', 'Parcialmente', 'Não'], 'health_general'), choice('SAU-07', 'Saúde', 'A confiança em Deus tem ajudado você a cuidar da saúde?', 'individual', ['Sim', 'Parcialmente', 'Prefere conversar'], 'health_general'),
  text('OUT-01', 'Outros', 'Existe algo importante que você gostaria de conversar?', 'individual'),
  text('ORA-01', 'Oração', 'Qual é o seu pedido de oração?', 'family', 'prayer'),
]

export function questionSnapshot(code: string): QuestionSnapshot | null { const question = OFFICIAL_QUESTIONS.find((item) => item.code === code); return question ? { ...question, options: [...question.options] } : null }
