import { AgendaService } from '../agenda/service'
import { currentDeviceId } from '../auth/device'
import { CommissionService } from '../commissions/service'
import type { CommissionAgendaItem, CommissionMeetingData } from '../commissions/types'
import { decryptRecord, encryptPayload } from '../crypto/vault'
import { db, type ApoioDatabase } from '../db/database'
import { VaultRepository } from '../db/repository'
import type { VaultRecord } from '../db/types'
import type { PersonEntity } from '../people/types'
import { COMMON_OFFICES, candidateReady, defaultFinalReport, defaultMeetingAgenda, defaultMeetingMinutes, fidelityNeedsReview, internalVote, officeAllowsAssociates, officeDefault, publicReport, publicReportText } from './core'
import type { CandidateStatus, NominationCandidate, NominationFormation, NominationMeeting, NominationObjection, NominationOfficialVote, NominationOffice, NominationProcessData, NominationProcessEntity, NominationReportVersion, NominationStatus, NominationTask, ObjectionDecision, OfficialVenue, OfficialVoteMode } from './types'

const now = () => new Date().toISOString()
const history = (action: string) => ({ id: crypto.randomUUID(), at: now(), action })
const decisionText = (result: string) => result === 'approved' ? 'aprovado' : result === 'rejected' ? 'rejeitado' : result === 'recorded' ? 'registrado' : 'adiado'

export class NominationService {
  private readonly repository: VaultRepository
  private readonly agenda: AgendaService
  private readonly commissions: CommissionService
  constructor(private readonly database: ApoioDatabase = db) { this.repository = new VaultRepository(database); this.agenda = new AgendaService(database); this.commissions = new CommissionService(database) }

  private async decode(record: VaultRecord, masterKey: CryptoKey): Promise<NominationProcessEntity | null> { const payload = await decryptRecord(masterKey, record); if (payload?.type !== 'nomination_process') return null; const data=payload.data as NominationProcessData; return { id: record.id, ...data, vacancyProcesses: data.vacancyProcesses??[], officialVotes:(data.officialVotes??[]).map((vote)=>({...vote,corrections:vote.corrections??[]})) } }
  async list(accountId: string, masterKey: CryptoKey, churchId?: string): Promise<NominationProcessEntity[]> { const decoded = await Promise.all((await this.repository.list(accountId, 'nomination_process')).map((record) => this.decode(record, masterKey))); return decoded.filter((item): item is NominationProcessEntity => Boolean(item)).filter((item) => !churchId || item.churchId === churchId).sort((a, b) => b.period.localeCompare(a.period)) }
  async get(accountId: string, masterKey: CryptoKey, id: string): Promise<NominationProcessEntity | null> { const record = await this.database.vaultRecords.get(id); return !record || record.accountId !== accountId || record.deletedAt ? null : this.decode(record, masterKey) }
  private async persist(accountId: string, masterKey: CryptoKey, process: NominationProcessEntity): Promise<NominationProcessEntity> { const data: NominationProcessData = { ...process, updatedAt: now() }; const envelope = await encryptPayload(masterKey, { schemaVersion: 1, type: 'nomination_process', data }, process.id); await this.repository.saveEncrypted(accountId, currentDeviceId(accountId), process.id, envelope, 'nomination_process'); return { id: process.id, ...data } }

  async create(accountId: string, masterKey: CryptoKey, churchId: string, period: string, leaderId = ''): Promise<NominationProcessEntity> {
    if (!churchId || !period.trim()) throw new Error('Informe a igreja e o período.')
    if ((await this.list(accountId, masterKey, churchId)).some((item) => item.period.toLocaleLowerCase('pt-BR') === period.trim().toLocaleLowerCase('pt-BR') && item.status !== 'archived')) throw new Error('Já existe um processo ativo para este período.')
    const timestamp = now(); const id = crypto.randomUUID()
    return this.persist(accountId, masterKey, { id, churchId, period: period.trim(), status: 'preparation', formation: { method: 'organizing_committee', organizingCommitteeIds: [], organizingVoteReference: '', committeeMemberIds: leaderId ? [leaderId] : [], presidentId: leaderId, secretaryId: '', districtLeaderId: leaderId, quorum: 0, electedAt: '', notes: '' }, offices: COMMON_OFFICES.map((office) => officeDefault(office.area, office.title, office.vacancies, office.allowsAssociates)), candidates: [], meetings: [], reports: [], objections: [], officialVotes: [], vacancyProcesses: [], tasks: [], history: [history('Processo criado')], createdAt: timestamp, updatedAt: timestamp })
  }

  async saveFormation(accountId: string, masterKey: CryptoKey, processId: string, formation: NominationFormation): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); if (!formation.presidentId || !formation.secretaryId || formation.committeeMemberIds.length === 0 || formation.quorum < 1) throw new Error('Informe membros, presidente, secretário(a) e quórum.'); if (!formation.committeeMemberIds.includes(formation.presidentId)) formation.committeeMemberIds = [formation.presidentId, ...formation.committeeMemberIds]; return this.persist(accountId, masterKey, { ...process, formation, status: 'formed', history: [...process.history, history('Comissão de Nomeações formada')] }) }
  async setStatus(accountId: string, masterKey: CryptoKey, processId: string, status: NominationStatus): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); return this.persist(accountId, masterKey, { ...process, status, history: [...process.history, history(`Situação alterada para ${status}`)] }) }
  async saveOffice(accountId: string, masterKey: CryptoKey, processId: string, office: NominationOffice): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); if (!office.title.trim() || office.vacancies < 1) throw new Error('Informe o cargo e a quantidade de vagas.'); if (/^pastor(?:a)?(?:\s|$)|pastor(?:a)?\s+associad/iu.test(office.title.trim())) throw new Error('Pastor e pastor associado não são cargos de nomeação local.'); const normalizado: NominationOffice = { ...office, allowsAssociates: Boolean(office.allowsAssociates) && officeAllowsAssociates(office.title) }; const exists = process.offices.some((item) => item.id === office.id); const offices = exists ? process.offices.map((item) => item.id === office.id ? normalizado : item) : [...process.offices, normalizado]; return this.persist(accountId, masterKey, { ...process, offices, history: [...process.history, history(exists ? `Cargo atualizado: ${office.title}` : `Cargo criado: ${office.title}`)] }) }
  async archiveOffice(accountId: string, masterKey: CryptoKey, processId: string, officeId: string): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const timestamp = now(); return this.persist(accountId, masterKey, { ...process, offices: process.offices.map((office) => office.id === officeId ? { ...office, status: 'archived', archivedAt: timestamp } : office), history: [...process.history, history('Cargo arquivado')] }) }

  async addCandidate(accountId: string, masterKey: CryptoKey, processId: string, officeId: string, person: PersonEntity, associate = false): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); if (person.currentChurchId !== process.churchId) throw new Error('Escolha uma pessoa cadastrada nesta igreja.'); const office = process.offices.find((item) => item.id === officeId); if (associate && !(office?.allowsAssociates && officeAllowsAssociates(office.title))) throw new Error('Este cargo não tem associados.'); if (process.candidates.some((candidate) => candidate.officeId === officeId && candidate.personId === person.id && candidate.status !== 'withdrawn')) throw new Error('Esta pessoa já foi indicada para o cargo.'); const fidelityAlert = fidelityNeedsReview(person); const candidate: NominationCandidate = { id: crypto.randomUUID(), officeId, personId: person.id, associate, status: 'suggested', confidentialNote: '', conversationDate: '', consent: false, refusalReason: '', eligibility: fidelityAlert ? 'pending' : 'confirmed', fidelityAlert }; return this.persist(accountId, masterKey, { ...process, status: 'nominating', candidates: [...process.candidates, candidate], history: [...process.history, history('Nova indicação registrada')] }) }
  async updateCandidate(accountId: string, masterKey: CryptoKey, processId: string, candidateId: string, patch: Partial<Pick<NominationCandidate, 'status' | 'confidentialNote' | 'conversationDate' | 'consent' | 'refusalReason' | 'eligibility'>>): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const candidates = process.candidates.map((candidate) => candidate.id === candidateId ? { ...candidate, ...patch } : candidate); return this.persist(accountId, masterKey, { ...process, candidates, status: candidates.some((candidate) => !candidate.consent) ? 'awaiting_consent' : process.status, history: [...process.history, history('Indicação atualizada')] }) }
  async voteCandidate(accountId: string, masterKey: CryptoKey, processId: string, candidateId: string, meetingId: string, favorable: number, against: number, abstentions: number): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const meeting = process.meetings.find((item) => item.id === meetingId); const candidate = process.candidates.find((item) => item.id === candidateId); if (!meeting || !candidate) throw new Error('Reunião ou indicação não encontrada.'); if (meeting.finalizedAt) throw new Error('O registro finalizado está protegido.'); const calculated = internalVote(favorable, against, abstentions, meeting.participantIds.length, meeting.quorum); if (!calculated.hasQuorum) throw new Error('Não há quórum para recomendar esta indicação.'); if (favorable + against === 0) throw new Error('É necessário ao menos um voto válido.'); if (favorable + against + abstentions > meeting.participantIds.length) throw new Error('O total de votos supera os participantes.'); let status: CandidateStatus = calculated.result === 'approved' ? 'recommended' : 'not_recommended'; if (calculated.result === 'approved' && (!candidate.consent || candidate.eligibility !== 'confirmed')) status = candidate.eligibility === 'pending' ? 'reviewing' : 'awaiting_conversation'; const vote = { favorable, against, abstentions, result: calculated.result, required: calculated.required, participantIds: [...meeting.participantIds], votedAt: now() }; return this.persist(accountId, masterKey, { ...process, candidates: process.candidates.map((item) => item.id === candidateId ? { ...item, status, vote } : item), history: [...process.history, history('Votação interna registrada')] }) }

  async createMeeting(accountId: string, masterKey: CryptoKey, processId: string): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const meeting: NominationMeeting = { id: crypto.randomUUID(), date: new Date().toISOString().slice(0, 10), time: '', location: '', presidentId: process.formation.presidentId, secretaryId: process.formation.secretaryId, participantIds: [...process.formation.committeeMemberIds], guestNames: [], quorum: process.formation.quorum, openingPrayer: '', reflection: '', agenda: ['Revisar cargos', 'Analisar indicações', 'Registrar consentimentos', 'Registrar pendências'], confidentialNotes: '', nextMeetingDate: '', corrections: [] }; return this.persist(accountId, masterKey, { ...process, meetings: [...process.meetings, meeting], history: [...process.history, history('Reunião criada')] }) }
  async updateMeeting(accountId: string, masterKey: CryptoKey, processId: string, meeting: NominationMeeting): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const current = process.meetings.find((item) => item.id === meeting.id); if (current?.finalizedAt) throw new Error('O registro finalizado está protegido. Use uma correção complementar.'); return this.persist(accountId, masterKey, { ...process, meetings: process.meetings.map((item) => item.id === meeting.id ? meeting : item), history: [...process.history, history('Reunião atualizada')] }) }
  async finalizeMeeting(accountId: string, masterKey: CryptoKey, processId: string, meetingId: string): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); return this.persist(accountId, masterKey, { ...process, meetings: process.meetings.map((meeting) => meeting.id === meetingId ? { ...meeting, finalizedAt: meeting.finalizedAt ?? now() } : meeting), history: [...process.history, history('Registro confidencial da reunião finalizado')] }) }
  async addMeetingCorrection(accountId: string, masterKey: CryptoKey, processId: string, meetingId: string, text: string): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); if (!text.trim()) throw new Error('Informe a correção.'); return this.persist(accountId, masterKey, { ...process, meetings: process.meetings.map((meeting) => meeting.id === meetingId ? { ...meeting, corrections: [...meeting.corrections, { id: crypto.randomUUID(), at: now(), text: text.trim() }] } : meeting), history: [...process.history, history('Correção complementar registrada')] }) }
  async addMeetingToAgenda(accountId: string, masterKey: CryptoKey, processId: string, meetingId: string): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const meeting = process.meetings.find((item) => item.id === meetingId); if (!meeting) throw new Error('Reunião não encontrada.'); if (meeting.agendaEventId) return process; const date = meeting.date || new Date().toISOString().slice(0, 10); const event = await this.agenda.createEvent(accountId, masterKey, { title: `Comissão de Nomeações - ${process.period}`, category: 'committee', churchId: process.churchId, location: meeting.location, address: '', visitTarget: 'none', sermonId: null, sermonSnapshot: null, startAt: `${date}T${meeting.time || '19:00'}`, endAt: `${date}T21:00`, allDay: false, reminderMinutes: 60, notes: 'Reunião da Comissão de Nomeações.', includeInItinerary: true, mondayException: true }); return this.persist(accountId, masterKey, { ...process, meetings: process.meetings.map((item) => item.id === meetingId ? { ...item, agendaEventId: event.id } : item), history: [...process.history, history('Reunião adicionada à Agenda pastoral')] }) }

  async generateReport(accountId: string, masterKey: CryptoKey, processId: string, people: PersonEntity[]): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const preview = publicReport(process, people); if (!preview.lines.length) throw new Error('Nenhuma indicação está pronta. Confirme consentimento, elegibilidade e votação interna.'); const report: NominationReportVersion = { id: crypto.randomUUID(), version: process.reports.length + 1, createdAt: now(), ...preview }; return this.persist(accountId, masterKey, { ...process, reports: [...process.reports, report], status: 'ready', history: [...process.history, history(`Versão ${report.version} do relatório gerada`)] }) }
  async updateReport(accountId: string, masterKey: CryptoKey, processId: string, report: NominationReportVersion): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); return this.persist(accountId, masterKey, { ...process, reports: process.reports.map((item) => item.id === report.id ? report : item), status: report.presentationDate ? 'presented' : process.status, history: [...process.history, history('Relatório revisado')] }) }
  async addObjection(accountId: string, masterKey: CryptoKey, processId: string, subject: string, details: string, date: string): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); if (!subject.trim()) throw new Error('Informe o assunto da objeção.'); const objection: NominationObjection = { id: crypto.randomUUID(), receivedAt: date || new Date().toISOString().slice(0, 10), subject: subject.trim(), confidentialDetails: details.trim(), decision: 'pending' }; return this.persist(accountId, masterKey, { ...process, objections: [...process.objections, objection], status: 'objections', history: [...process.history, history('Objeção recebida e devolvida à comissão')] }) }
  async decideObjection(accountId: string, masterKey: CryptoKey, processId: string, objectionId: string, decision: ObjectionDecision): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); return this.persist(accountId, masterKey, { ...process, objections: process.objections.map((item) => item.id === objectionId ? { ...item, decision, decidedAt: now() } : item), status: decision === 'awaiting_presentation' || decision === 'changed' ? 'ready' : process.status, history: [...process.history, history('Objeção analisada pela comissão')] }) }

  async prepareOfficialVote(accountId: string, masterKey: CryptoKey, processId: string, mode: OfficialVoteMode, venue: OfficialVenue, officeId?: string): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const report = process.reports.at(-1); if (!report) throw new Error('Gere o relatório antes de preparar a votação oficial.'); const timestamp = now(); let administrativeMeetingId: string | undefined
    if (venue === 'administrative') { const config = await this.commissions.config(accountId, masterKey, process.churchId); const proposal = `aprovar e registrar o relatório da Comissão de Nomeações para o período ${process.period}`; const item: CommissionAgendaItem = { id: crypto.randomUUID(), order: 1, title: `Relatório da Comissão de Nomeações - ${process.period}`, department: 'Comissão de Nomeações', description: 'Relatório apresentado à igreja.', proposal, decisionType: 'approve', customDecisionType: '', destination: 'record', responsibleId: process.formation.secretaryId, dueDate: '', privateNotes: '', sourceMeetingId: process.id, sourceVoteNumber: `Nomeações ${process.period}` }; const meeting: CommissionMeetingData = { churchId: process.churchId, kind: 'administrative', date: report.officialVoteDate || new Date().toISOString().slice(0, 10), time: '', location: '', presidentId: process.formation.presidentId || config?.boardPresidentId || '', secretaryId: process.formation.secretaryId || config?.secretaryId || '', participantIds: [], guestNames: [], votingGuestNames: [], openingPrayer: '', reflection: '', notes: '', agenda: [item], createdAt: timestamp, updatedAt: timestamp }; administrativeMeetingId = (await this.commissions.saveMeeting(accountId, masterKey, meeting)).id }
    const vote: NominationOfficialVote = { id: crypto.randomUUID(), mode, venue, ...(officeId ? { officeId } : {}), date: report.officialVoteDate || new Date().toISOString().slice(0, 10), time: '', location: '', presidentId: process.formation.presidentId, secretaryId: process.formation.secretaryId, participantIds: [], quorum: process.formation.quorum, favorable: 0, against: 0, abstentions: 0, result: 'deferred', required: 0, corrections: [], ...(administrativeMeetingId ? { administrativeMeetingId } : {}) }; return this.persist(accountId, masterKey, { ...process, officialVotes: [...process.officialVotes, vote], status: 'voting', history: [...process.history, history('Votação oficial preparada')] }) }
  async updateOfficialVote(accountId: string, masterKey: CryptoKey, processId: string, vote: NominationOfficialVote): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const current = process.officialVotes.find((item) => item.id === vote.id); if (current?.finalizedAt) throw new Error('A votação oficial finalizada está protegida.'); return this.persist(accountId, masterKey, { ...process, officialVotes: process.officialVotes.map((item) => item.id === vote.id ? vote : item), history: [...process.history, history('Dados da votação oficial atualizados')] }) }
  async voteOfficial(accountId: string, masterKey: CryptoKey, processId: string, voteId: string, favorable: number, against: number, abstentions: number): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const vote = process.officialVotes.find((item) => item.id === voteId); if (!vote) throw new Error('Votação oficial não encontrada.'); if (vote.finalizedAt) throw new Error('A votação oficial finalizada está protegida.'); const calculated = internalVote(favorable, against, abstentions, vote.participantIds.length, vote.quorum); if (!calculated.hasQuorum) throw new Error('Não há quórum para a votação oficial.'); if (favorable + against === 0) throw new Error('É necessário ao menos um voto válido.'); if (favorable + against + abstentions > vote.participantIds.length) throw new Error('O total de votos supera os participantes.'); const finalizedAt = now(); const offices = process.offices.map((office) => vote.mode === 'complete' || office.id === vote.officeId ? { ...office, officialStatus: calculated.result === 'approved' ? 'elected' as const : 'referred_back' as const, status: calculated.result === 'approved' ? 'filled' as const : 'open' as const } : office); const candidates = process.candidates.map((candidate) => (vote.mode === 'complete' || candidate.officeId === vote.officeId) && candidateReady(candidate) && calculated.result === 'approved' ? { ...candidate, electedAt: finalizedAt } : candidate); const officialVotes = process.officialVotes.map((item) => item.id === voteId ? { ...item, favorable, against, abstentions, result: calculated.result, required: calculated.required, finalizedAt } : item); const reports = process.reports.map((report, index) => index === process.reports.length - 1 ? { ...report, officialVoteDate: vote.date } : report); return this.persist(accountId, masterKey, { ...process, offices, candidates, officialVotes, reports, status: calculated.result === 'approved' ? 'completed' : 'nominating', history: [...process.history, history('Votação oficial finalizada')] }) }

  async addOfficialCorrection(accountId: string, masterKey: CryptoKey, processId: string, voteId: string, text: string): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); if (!text.trim()) throw new Error('Informe a correção complementar.'); return this.persist(accountId, masterKey, { ...process, officialVotes: process.officialVotes.map((vote) => vote.id === voteId ? { ...vote, corrections: [...vote.corrections, { id: crypto.randomUUID(), at: now(), text: text.trim() }] } : vote), history: [...process.history, history('Correção complementar da votação oficial registrada')] }) }
  async fillVacancy(accountId: string, masterKey: CryptoKey, processId: string, officeId: string, route: 'board' | 'permanent_nominating' = 'board'): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const vacancy = { id: crypto.randomUUID(), officeId, route, startedAt: now(), sourceVoteReference: '' }; return this.persist(accountId, masterKey, { ...process, status: 'nominating', offices: process.offices.map((office) => office.id === officeId ? { ...office, status: 'open', officialStatus: 'vacant' } : office), vacancyProcesses: [...process.vacancyProcesses, vacancy], history: [...process.history, history(`Preenchimento de vaga iniciado pela ${route === 'board' ? 'Comissão Diretiva' : 'Comissão de Nomeações permanente'}`)] }) }
  async addTask(accountId: string, masterKey: CryptoKey, processId: string, title: string, responsibleId: string, dueDate: string): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const task: NominationTask = { id: crypto.randomUUID(), title: title.trim(), responsibleId, dueDate, status: 'pending' }; return this.persist(accountId, masterKey, { ...process, tasks: [...process.tasks, task], history: [...process.history, history('Pendência criada')] }) }
  async updateTask(accountId: string, masterKey: CryptoKey, processId: string, taskId: string, status: NominationTask['status']): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); return this.persist(accountId, masterKey, { ...process, tasks: process.tasks.map((task) => task.id === taskId ? { ...task, status } : task), history: [...process.history, history('Pendência atualizada')] }) }
  async addTaskToAgenda(accountId: string, masterKey: CryptoKey, processId: string, taskId: string): Promise<NominationProcessEntity> { const process = await this.required(accountId, masterKey, processId); const task = process.tasks.find((item) => item.id === taskId); if (!task) throw new Error('Pendência não encontrada.'); if (task.agendaEventId) return process; const date = task.dueDate || new Date().toISOString().slice(0, 10); const event = await this.agenda.createEvent(accountId, masterKey, { title: task.title, category: 'committee', churchId: process.churchId, location: '', address: '', visitTarget: 'none', sermonId: null, sermonSnapshot: null, startAt: `${date}T08:00`, endAt: `${date}T09:00`, allDay: false, reminderMinutes: 60, notes: 'Pendência da Comissão de Nomeações.', includeInItinerary: true, mondayException: true }); return this.persist(accountId, masterKey, { ...process, tasks: process.tasks.map((item) => item.id === taskId ? { ...item, agendaEventId: event.id } : item), history: [...process.history, history('Pendência adicionada à Agenda pastoral')] }) }

  reportText(churchName: string, process: NominationProcessEntity, report: NominationReportVersion, includeNames = false): string { return publicReportText(churchName, process, report, includeNames) }
  /**
   * Modelo de pauta: usa o texto salvo pelo pastor ou o modelo pastoral padrão.
   *
   * Um modelo salvo é texto livre que o pastor escreveu, e o aplicativo não
   * tem como saber quais palavras ali são nomes de pessoas. Por isso, com a
   * confirmação de nomes desmarcada, ele não é servido: vale o modelo padrão,
   * que passa por `personName` e obedece à escolha. Servir o texto salvo seria
   * dizer "sem nomes" e entregar os nomes que o pastor digitou.
   */
  meetingAgendaTemplate(churchName: string, process: NominationProcessEntity, meeting: NominationMeeting, personName: (id: string) => string, includeNames = false): string {
    return includeNames && meeting.agendaTemplate?.trim() ? meeting.agendaTemplate : defaultMeetingAgenda(churchName, process, meeting, personName)
  }

  /** Modelo de ata, com a mesma regra do modelo de pauta. */
  meetingMinutesTemplate(churchName: string, process: NominationProcessEntity, meeting: NominationMeeting, personName: (id: string) => string, includeNames = false): string {
    return includeNames && meeting.minutesTemplate?.trim() ? meeting.minutesTemplate : defaultMeetingMinutes(churchName, process, meeting, personName)
  }

  /** Modelo do relatório final, com a mesma regra dos demais. */
  finalReportTemplate(churchName: string, process: NominationProcessEntity, report: NominationReportVersion, includeNames = false): string {
    return includeNames && report.reportTemplate?.trim() ? report.reportTemplate : defaultFinalReport(churchName, process, report, includeNames)
  }

  async saveMeetingTemplates(accountId: string, masterKey: CryptoKey, processId: string, meetingId: string, patch: { agendaTemplate?: string; minutesTemplate?: string }): Promise<NominationProcessEntity> {
    const process = await this.required(accountId, masterKey, processId)
    return this.persist(accountId, masterKey, { ...process, meetings: process.meetings.map((meeting) => meeting.id === meetingId ? { ...meeting, ...patch } : meeting) })
  }

  async saveReportTemplate(accountId: string, masterKey: CryptoKey, processId: string, reportId: string, text: string): Promise<NominationProcessEntity> {
    const process = await this.required(accountId, masterKey, processId)
    return this.persist(accountId, masterKey, { ...process, reports: process.reports.map((report) => report.id === reportId ? { ...report, reportTemplate: text } : report) })
  }

  internalAgenda(process: NominationProcessEntity, meeting: NominationMeeting, personName: (id: string) => string): string { return [`Comissão de Nomeações - ${process.period}`, `Data: ${meeting.date} · ${meeting.time || 'horário a definir'} · ${meeting.location || 'local a definir'}`, `Presidente: ${personName(meeting.presidentId)} · Secretário(a): ${personName(meeting.secretaryId)}`, `Quórum: ${meeting.participantIds.length} presentes; mínimo ${meeting.quorum}`, ...meeting.agenda.map((item, index) => `${index + 1}. ${item}`)].join('\n\n') }
  internalRecord(process: NominationProcessEntity, meeting: NominationMeeting, personName: (id: string) => string): string { return [`Registro confidencial - Comissão de Nomeações - ${process.period}`, `Data: ${meeting.date} · ${meeting.time || 'horário a definir'} · ${meeting.location || 'local a definir'}`, `Participantes: ${meeting.participantIds.map(personName).join(', ')}`, `Quórum: ${meeting.participantIds.length} presentes; mínimo ${meeting.quorum}`, meeting.confidentialNotes ? `Observações confidenciais: ${meeting.confidentialNotes}` : '', ...process.candidates.filter((candidate) => candidate.vote).map((candidate) => `${personName(candidate.personId)}: ${candidate.vote?.favorable} favoráveis, ${candidate.vote?.against} contrários, ${candidate.vote?.abstentions} abstenções; resultado ${decisionText(candidate.vote?.result ?? 'deferred')}.`), `Assinaturas: ${personName(meeting.presidentId)} e ${personName(meeting.secretaryId)}`].filter(Boolean).join('\n\n') }
  officialAgenda(process: NominationProcessEntity, vote: NominationOfficialVote): string { return [`Votação oficial - Comissão de Nomeações`, `Período: ${process.period}`, `Data: ${vote.date} · ${vote.time || 'horário a definir'} · ${vote.location || 'local a definir'}`, `PROPÕE-SE aprovar e registrar o relatório da Comissão de Nomeações para o período ${process.period}.`].join('\n\n') }
  officialMinutes(process: NominationProcessEntity, vote: NominationOfficialVote, personName: (id: string) => string): string { return [`Ata da votação oficial - Comissão de Nomeações`, `Período: ${process.period}`, `VOTADO aprovar e registrar o relatório da Comissão de Nomeações para o período ${process.period}.`, `Favoráveis: ${vote.favorable}; contrários: ${vote.against}; abstenções: ${vote.abstentions}; resultado: ${decisionText(vote.result)}.`, `Assinaturas: ${personName(vote.presidentId)} e ${personName(vote.secretaryId)}`].join('\n\n') }

  private async required(accountId: string, masterKey: CryptoKey, id: string): Promise<NominationProcessEntity> { const process = await this.get(accountId, masterKey, id); if (!process) throw new Error('Processo de nomeações não encontrado.'); return process }
}
