import { expect, test, type Page } from '@playwright/test'
import { agendaDate, futureDate, isoDate, isoDateTime } from './dates'
import { navigateInsideApp } from './navigation'

const email = 'v1.cuidado.e2e@example.invalid'
const password = 'senha-ficticia-cuidado-2026'

async function foundation(page: Page) {
  await page.goto('/acesso')
  await page.getByLabel('E-mail').fill(email)
  await page.getByLabel('Senha').fill(password)
  await page.getByRole('button', { name: 'Criar conta' }).click()
  await page.getByRole('button', { name: 'Já guardei em local seguro' }).click()
  await page.getByLabel('Nome do distrito').fill('Distrito Cuidado Fictício')
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByRole('button', { name: 'Cadastrar manualmente' }).click()
  await page.getByRole('link', { name: 'Ir para o início' }).click()
  await navigateInsideApp(page, '/app/distrito', page.getByRole('heading', { name: 'Distrito Cuidado Fictício' }))
  await page.getByRole('link', { name: 'Nova igreja' }).click()
  await page.getByLabel(/Nome da igreja/).fill('Igreja Esperança Fictícia')
  await page.getByLabel(/Tipo/).selectOption('organized_church')
  await page.getByRole('button', { name: 'Salvar igreja' }).click()
  await expect(page.getByRole('heading', { name: 'Igreja Esperança Fictícia', exact: true })).toBeVisible()
  await navigateInsideApp(page, '/app/pessoas/nova', page.getByLabel(/Nome completo/))
  await page.getByLabel(/Nome completo/).fill('Pessoa Cuidado Fictícia')
  await page.getByLabel(/Igreja/).selectOption({ label: 'Igreja Esperança Fictícia' })
  await page.getByRole('button', { name: 'Salvar pessoa' }).click()
  await expect(page.getByRole('heading', { name: 'Pessoa Cuidado Fictícia', exact: true })).toBeVisible()
  await navigateInsideApp(page, '/app/familias/nova', page.getByLabel(/Nome da família/))
  await page.getByLabel(/Nome da família/).fill('Família Cuidado Fictícia')
  await page.getByLabel(/Igreja principal/).selectOption({ label: 'Igreja Esperança Fictícia' })
  await page.getByText('Pessoa Cuidado Fictícia').click()
  await page.getByRole('button', { name: 'Salvar família' }).click()
  await expect(page.getByRole('heading', { name: 'Família Cuidado Fictícia', exact: true })).toBeVisible()
}

test('agenda, visita versionada, cuidado e rodada funcionam no armazenamento offline', async ({ page, context }) => {
  await foundation(page)
  const appointment = agendaDate()
  await navigateInsideApp(page, '/app/agenda/novo', page.getByLabel('Título'))
  await page.getByLabel('Título').fill('Visita Agendada Fictícia')
  await page.getByLabel('Início').fill(isoDateTime(appointment, 14))
  await page.getByLabel('Término').fill(isoDateTime(appointment, 15))
  await page.getByRole('button', { name: 'Salvar compromisso' }).click()
  await expect(page.getByRole('link', { name: /Abrir Visita Agendada Fictícia/ })).toBeVisible()
  await navigateInsideApp(page, '/app/cuidados', page.getByText('Família Cuidado Fictícia', { exact: true }))
  await page.getByLabel('Nome da rodada').fill('Rodada Cuidado Fictícia')
  await page.getByText('Família Cuidado Fictícia').click()
  await page.getByRole('button', { name: 'Iniciar rodada' }).click()
  await expect(page.getByText('0 de 1 famílias visitadas')).toBeVisible()
  const visitChurch = page.getByRole('combobox', { name: /^Igreja(?:$|\s)/ })
  await navigateInsideApp(page, '/app/visitas/nova', visitChurch)
  await visitChurch.selectOption({ label: 'Igreja Esperança Fictícia' })
  await expect(page.getByLabel('Cadastro visitado')).toContainText('Família Cuidado Fictícia')
  await page.getByLabel('Cadastro visitado').selectOption({ label: 'Família Cuidado Fictícia' })
  await page.getByLabel(/Agendamento vinculado/).selectOption({ label: 'Visita Agendada Fictícia' })
  await page.getByLabel('Rodada (opcional)').selectOption({ label: 'Rodada Cuidado Fictícia' })
  const question = page.locator('.question-card').filter({ hasText: 'COM-01' })
  await question.locator('input[type="checkbox"]').check()
  await question.getByRole('combobox').selectOption('Sim')
  await page.getByLabel('Pedido opcional').fill('Pedido de oração inteiramente fictício')
  await page.getByRole('combobox', { name: 'Acompanhamento', exact: true }).selectOption('call')
  await page.getByLabel('Prazo do acompanhamento').fill(isoDate(futureDate(2)))
  await page.getByLabel('Título da tarefa').fill('Tarefa pastoral fictícia')
  await page.getByLabel('Prazo da tarefa').fill(isoDate(futureDate(3)))
  await page.getByRole('button', { name: 'Finalizar visita' }).click()
  const visitVersion = page.getByText(/^Retrato imutável · versão \d+$/)
  await expect(visitVersion).toHaveText('Retrato imutável · versão 1')
  await page.getByRole('button', { name: 'Registrar correção' }).click()
  await page.getByLabel('Motivo da correção').fill('Ajuste fictício')
  await page.getByRole('button', { name: 'Salvar como versão 2' }).click()
  await expect(visitVersion).toHaveText('Retrato imutável · versão 2')
  await navigateInsideApp(page, '/app/cuidados', page.getByText('Rodada Cuidado Fictícia'))
  await expect(page.getByText('Rodada Cuidado Fictícia')).toBeVisible()
  await expect(page.getByText('1 de 1 famílias visitadas')).toBeVisible()
  await context.setOffline(true)
  await page.reload()
  await page.getByLabel('Senha').fill(password)
  await page.getByRole('button', { name: 'Entrar' }).click()
  await navigateInsideApp(page, '/app/visitas', page.getByText('Família Cuidado Fictícia'))
  await expect(page.getByText('Família Cuidado Fictícia')).toBeVisible()
})
