import { currentDeviceId } from '../auth/device'
import { decryptPayload, encryptPayload } from '../crypto/vault'
import { db, type ApoioDatabase } from '../db/database'
import { VaultRepository } from '../db/repository'
import type { SermonEntity, SermonInput } from './types'

function validate(input: SermonInput): void { if (!input.title.trim()) throw new Error('Informe o título do sermão.'); if (!input.mainText.trim()) throw new Error('Informe o texto bíblico principal.'); if (input.title.length > 180 || input.content.length > 20_000 || input.notes.length > 4_000) throw new Error('Um dos campos excede o limite permitido.') }
export class SermonService {
  private readonly repository: VaultRepository
  constructor(private readonly database: ApoioDatabase = db) { this.repository = new VaultRepository(database) }
  async list(accountId: string, masterKey: CryptoKey): Promise<SermonEntity[]> { const records = await this.repository.list(accountId, 'sermon'); const items = await Promise.all(records.map(async (record) => { const payload = await decryptPayload(masterKey, record); return payload.type === 'sermon' ? { id: record.id, ...(payload.data as Omit<SermonEntity, 'id'>) } : null })); return items.filter((item): item is SermonEntity => Boolean(item)).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)) }
  async get(accountId: string, masterKey: CryptoKey, id: string): Promise<SermonEntity | null> { return (await this.list(accountId, masterKey)).find((item) => item.id === id) ?? null }
  async create(accountId: string, masterKey: CryptoKey, input: SermonInput): Promise<SermonEntity> { validate(input); const id = crypto.randomUUID(); const now = new Date().toISOString(); const data = { ...input, title: input.title.trim(), theme: input.theme.trim(), mainText: input.mainText.trim(), complementaryTexts: input.complementaryTexts.trim(), objective: input.objective.trim(), introduction: input.introduction.trim(), content: input.content.trim(), conclusion: input.conclusion.trim(), appeal: input.appeal.trim(), notes: input.notes.trim(), tags: input.tags.map((tag) => tag.trim()).filter(Boolean), createdAt: now, updatedAt: now }; await this.repository.saveEncrypted(accountId, currentDeviceId(), id, await encryptPayload(masterKey, { schemaVersion: 1, type: 'sermon', data }, id), 'sermon'); return { id, ...data } }
  async update(accountId: string, masterKey: CryptoKey, id: string, input: SermonInput): Promise<SermonEntity> { const current = await this.get(accountId, masterKey, id); if (!current) throw new Error('Sermão não encontrado.'); validate(input); const data = { ...input, title: input.title.trim(), theme: input.theme.trim(), mainText: input.mainText.trim(), complementaryTexts: input.complementaryTexts.trim(), objective: input.objective.trim(), introduction: input.introduction.trim(), content: input.content.trim(), conclusion: input.conclusion.trim(), appeal: input.appeal.trim(), notes: input.notes.trim(), tags: input.tags.map((tag) => tag.trim()).filter(Boolean), createdAt: current.createdAt, updatedAt: new Date().toISOString() }; await this.repository.saveEncrypted(accountId, currentDeviceId(), id, await encryptPayload(masterKey, { schemaVersion: 1, type: 'sermon', data }, id), 'sermon'); return { id, ...data } }
  async remove(accountId: string, masterKey: CryptoKey, id: string): Promise<void> { if (!await this.get(accountId, masterKey, id)) throw new Error('Sermão não encontrado.'); await this.repository.deleteEncrypted(accountId, currentDeviceId(), id, await encryptPayload(masterKey, { schemaVersion: 1, type: 'sermon_tombstone', data: { deletedAt: new Date().toISOString() } }, id)) }
}
