import { useReloadOnSync } from '../sync/useReloadOnSync'
import { BookOpen, CalendarDays, ChevronLeft, ChevronRight, Clock3, Download, Edit3, MapPin, Plus, Trash2, TriangleAlert } from 'lucide-react'
import { useCallback, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { AgendaService, mondayRestItems } from '../agenda/service'
import { downloadItineraryPdf, itineraryItems } from '../agenda/itineraryPdf'
import { AGENDA_CATEGORY_LABELS, type AgendaCategory, type AgendaEventEntity } from '../agenda/types'
import { useAuthVault } from '../auth/AuthVaultContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { DistrictService } from '../district/service'
import type { ChurchEntity } from '../district/types'
import { dayStart, eventOccursOnDay, hoursForDay, moveAgendaAnchor, periodBounds, sameDay, type AgendaView } from '../agenda/calendar'
import { localDateKey } from '../shared/dates'

const agenda = new AgendaService(); const districts = new DistrictService()
const VIEWS: Array<{ id: AgendaView; label: string }> = [{ id: 'day', label: 'Dia' }, { id: 'week', label: 'Semana' }, { id: 'month', label: 'Mês' }, { id: 'list', label: 'Lista' }]
const WEEKDAY_LABELS = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb']
function localDateTime(value: Date, hour = 8): string { return `${localDateKey(value)}T${String(hour).padStart(2, '0')}:00` }
const localKey = localDateKey
const moveAnchor = moveAgendaAnchor
function displayDate(value: string, allDay: boolean): string { return new Intl.DateTimeFormat('pt-BR', allDay ? { weekday: 'short', day: '2-digit', month: 'short' } : { weekday: 'short', day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) }
function eventTime(event: AgendaEventEntity): string { return event.allDay ? 'Dia todo' : new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit' }).format(new Date(event.startAt)) }
function categoryClass(category: AgendaCategory | 'rest'): string { return `agenda-category agenda-category--${category}` }

function EventChip({ event, compact = false }: { event: AgendaEventEntity; compact?: boolean }) {
  return <Link className={`${categoryClass(event.category)} ${compact ? 'agenda-category--compact' : ''}`} to={`/app/agenda/${event.id}/editar`} aria-label={`Abrir ${event.title}, ${AGENDA_CATEGORY_LABELS[event.category]}`}><span>{eventTime(event)}</span><strong>{event.title}</strong>{event.category === 'preaching' && event.sermonSnapshot && <small><BookOpen />{event.sermonSnapshot.title}</small>}</Link>
}

export function AgendaPage() {
  const { account, masterKey } = useAuthVault(); const [events, setEvents] = useState<AgendaEventEntity[]>([]); const [churches, setChurches] = useState<ChurchEntity[]>([]); const [view, setView] = useState<AgendaView>('week'); const [anchor, setAnchor] = useState(() => new Date()); const [selected, setSelected] = useState<Set<string>>(new Set()); const [comNomes, setComNomes] = useState(false); const [pdfOpen, setPdfOpen] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { if (!account || !masterKey) return; const district = await districts.getDistrict(account.id, masterKey); const [nextEvents, nextChurches] = await Promise.all([agenda.listEvents(account.id, masterKey), district ? districts.listChurches(account.id, masterKey, district.id) : []]); setEvents(nextEvents); setChurches(nextChurches); setSelected(new Set(nextEvents.filter(({ includeInItinerary }) => includeInItinerary).map(({ id }) => id))) }, [account, masterKey])
  useReloadOnSync(load)
  const [from, to] = useMemo(() => periodBounds(view, anchor), [anchor, view]); const periodEvents = events.filter((event) => new Date(event.startAt) <= to && new Date(event.endAt) >= from); const visibleEvents = periodEvents; const restItems = mondayRestItems(from, to); const churchName = (id: string | null) => churches.find((church) => church.id === id)?.name
  const days = useMemo(() => { const output: Date[] = []; const cursor = dayStart(from); while (cursor <= to) { output.push(new Date(cursor)); cursor.setDate(cursor.getDate() + 1) } return output }, [from, to])
  const monthDays = useMemo(() => { const first = new Date(anchor.getFullYear(), anchor.getMonth(), 1); const cursor = new Date(first); cursor.setDate(first.getDate() - first.getDay()); return Array.from({ length: 42 }, (_, index) => { const date = new Date(cursor); date.setDate(cursor.getDate() + index); return date }) }, [anchor])
  const label = view === 'day' ? new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(anchor) : view === 'week' || view === 'list' ? `${new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short' }).format(from)} — ${new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short' }).format(to)}` : new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(anchor)
  async function remove(event: AgendaEventEntity) { if (!account || !masterKey || !window.confirm('Remover este compromisso?')) return; try { await agenda.deleteEvent(account.id, masterKey, event.id); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível remover.') } }
  function toggle(id: string) { setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next }) }
  function generatePdf() { const items = itineraryItems(events, from, to, selected, churchName); if (!items.length) { setError('Selecione ao menos um compromisso ou uma segunda-feira de folga.'); return } downloadItineraryPdf(items, view === 'day' ? displayDate(anchor.toISOString(), true) : new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long' }).format(from), comNomes); setError('') }
  const newEvent = (date = anchor, hour = 8) => `/app/agenda/novo?inicio=${encodeURIComponent(localDateTime(date, hour))}`
  const eventsOn = (date: Date) => visibleEvents.filter((event) => eventOccursOnDay(event, date))

  function renderList() { return <div className="agenda-list">{[...restItems, ...visibleEvents].sort((a, b) => a.startAt.localeCompare(b.startAt)).map((item) => { const rest = item.category === 'rest'; const event = rest ? null : item as AgendaEventEntity; return <article className={`agenda-item ${rest ? 'agenda-item--rest' : ''}`} key={item.id}><div className="agenda-item__date"><CalendarDays /><span>{displayDate(item.startAt, item.allDay)}</span></div><div className="agenda-item__body"><span className={categoryClass(item.category)}>{rest ? 'Folga de segunda-feira' : AGENDA_CATEGORY_LABELS[event!.category]}</span><h3>{event ? <Link to={`/app/agenda/${event.id}/editar`}>{event.title}</Link> : item.title}</h3>{event && <div className="agenda-item__meta">{event.allDay ? <span><Clock3 />Dia todo</span> : <span><Clock3 />até {new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit' }).format(new Date(event.endAt))}</span>}{(event.location || churchName(event.churchId)) && <span><MapPin />{event.location || churchName(event.churchId)}</span>}{event.sermonSnapshot && <span><BookOpen />{event.sermonSnapshot.title}</span>}</div>}</div>{event ? <div className="agenda-item__actions">{event.category === 'visit' && <Link className="icon-button" aria-label={`Registrar visita ${event.title}`} to={`/app/visitas/nova?agenda=${event.id}`}><CalendarDays /></Link>}{event.sermonId && <Link className="icon-button" aria-label={`Abrir sermão de ${event.title}`} to={`/app/sermoes/${event.sermonId}`}><BookOpen /></Link>}<Link className="icon-button" aria-label={`Editar ${event.title}`} to={`/app/agenda/${event.id}/editar`}><Edit3 /></Link><button className="icon-button danger-icon" aria-label={`Remover ${event.title}`} onClick={() => void remove(event)}><Trash2 /></button></div> : <div className="agenda-rest-note"><TriangleAlert />Exige exceção explícita</div>}</article> })}</div> }
  function renderDay() { const dayEvents = eventsOn(anchor); return <section className="agenda-day" aria-label="Grade do dia">{hoursForDay(dayEvents, anchor).map((hour) => { const hourEvents = dayEvents.filter((event) => { if (event.allDay) return false; const start = new Date(event.startAt); return (sameDay(start, anchor) ? start.getHours() : 0) === hour }); return <div className="agenda-time-row" key={hour}><time>{String(hour).padStart(2, '0')}:00</time><Link className="agenda-time-slot" to={newEvent(anchor, hour)} aria-label={`Criar compromisso às ${String(hour).padStart(2, '0')}:00`}><span>+</span></Link><div className="agenda-time-events">{hourEvents.map((event) => <EventChip event={event} key={event.id} />)}</div></div> })}{dayEvents.filter(({ allDay }) => allDay).map((event) => <EventChip event={event} key={event.id} />)}</section> }
  function renderWeek() { return <section className="agenda-week" aria-label="Grade semanal">{days.map((day) => <div className="agenda-week-day" key={localKey(day)}><header><span>{WEEKDAY_LABELS[day.getDay()]}</span><strong>{day.getDate()}</strong></header><Link className="agenda-week-add" to={newEvent(day)} aria-label={`Criar compromisso em ${new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long' }).format(day)}`}>+ Novo</Link>{eventsOn(day).map((event) => <EventChip event={event} key={event.id} compact />)}{sameDay(day, new Date()) && <span className="agenda-today-marker">Hoje</span>}</div>)}</section> }
  function renderMonth() { return <section className="agenda-month" aria-label="Calendário mensal">{WEEKDAY_LABELS.map((day) => <strong className="agenda-month-weekday" key={day}>{day}</strong>)}{monthDays.map((day) => { const inMonth = day.getMonth() === anchor.getMonth(); return <div className={`agenda-month-day ${inMonth ? '' : 'agenda-month-day--outside'} ${sameDay(day, new Date()) ? 'agenda-month-day--today' : ''}`} key={localKey(day)}><Link to={newEvent(day)} aria-label={`Criar compromisso em ${new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long' }).format(day)}`}><span>{day.getDate()}</span></Link><div>{eventsOn(day).slice(0, 3).map((event) => <EventChip event={event} key={event.id} compact />)}{eventsOn(day).length > 3 && <small>+{eventsOn(day).length - 3} compromisso(s)</small>}</div></div> })}</section> }

  return <div className="page-stack agenda-page"><header className="page-hero agenda-hero"><div><p className="eyebrow">Organize sua semana</p><h1>Agenda</h1></div><div className="page-actions"><Button variant="secondary" onClick={() => setPdfOpen((value) => !value)} icon={<Download />}>Itinerário</Button><Link className="button" to={newEvent()}><Plus />Novo compromisso</Link></div></header>{error && <div className="alert alert--error" role="alert">{error}</div>}<Card className="agenda-controls"><div className="agenda-view-tabs" role="tablist" aria-label="Visualização da agenda">{VIEWS.map((item) => <button key={item.id} type="button" role="tab" aria-selected={view === item.id} className={view === item.id ? 'active' : ''} onClick={() => setView(item.id)}>{item.label}</button>)}</div><div className="agenda-toolbar"><Button variant="secondary" aria-label="Período anterior" onClick={() => setAnchor((current) => moveAnchor(current, view, -1))} icon={<ChevronLeft />}>Anterior</Button><h2 aria-live="polite">{label}</h2><Button variant="secondary" aria-label="Próximo período" onClick={() => setAnchor((current) => moveAnchor(current, view, 1))} icon={<ChevronRight />}>Próximo</Button><Button variant="secondary" className="agenda-today-button" onClick={() => setAnchor(new Date())}>Hoje</Button></div></Card>{pdfOpen && <Card eyebrow="Itinerário local" title="Selecionar compromissos"><div className="itinerary-selection">{visibleEvents.map((event) => <label key={event.id}><input type="checkbox" checked={selected.has(event.id)} onChange={() => toggle(event.id)} /><span><strong>{event.title}</strong><small>{AGENDA_CATEGORY_LABELS[event.category]} · {displayDate(event.startAt, event.allDay)}</small></span></label>)}</div><div className="alert alert--success">As {restItems.length} segunda(s)-feira(s) de folga entram automaticamente.</div><label className="confirmation-check"><input type="checkbox" checked={comNomes} onChange={(event) => setComNomes(event.target.checked)} /><span><strong>Incluir nomes neste relatório</strong><small>Sem marcar, saem data, tipo e local. Com nomes, o arquivo pode conter dados pessoais: compartilhe com cuidado.</small></span></label><Button onClick={generatePdf} icon={<Download />}>Baixar itinerário</Button></Card>}{view === 'day' ? renderDay() : view === 'week' ? renderWeek() : view === 'month' ? renderMonth() : renderList()}{!visibleEvents.length && <div className="empty-state"><CalendarDays /><strong>Nenhum compromisso neste período</strong><p>Nenhum compromisso nesta semana. Crie uma visita, pregação ou reunião.</p><Link className="button" to={newEvent()}><Plus />Criar compromisso</Link></div>}</div>
}
