import { useReloadOnSync } from '../sync/useReloadOnSync'
import { CheckCircle2, Circle, Eye, EyeOff, Heart, ListChecks, Plus, RotateCcw, UsersRound } from 'lucide-react'
import { type FormEvent, useCallback, useState } from 'react'
import { Link } from 'react-router-dom'
import type { VisitEntity } from '../care/types'
import { agruparVisitasPorIgreja } from '../care/visitasPorIgreja'
import { useAuthVault } from '../auth/AuthVaultContext'
import { CareService } from '../care/service'
import { FOLLOW_UP_LABELS, type FollowUpEntity, type PrayerRequestEntity, type TaskEntity, type VisitRoundEntity } from '../care/types'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Field } from '../components/ui/Field'
import { DistrictService } from '../district/service'
import type { ChurchEntity } from '../district/types'
import { FamilyService } from '../families/service'
import type { FamilyEntity } from '../families/types'
import { PeopleService } from '../people/service'
import type { PersonEntity } from '../people/types'

const care = new CareService(); const familiesService = new FamilyService(); const peopleService = new PeopleService(); const districts = new DistrictService()
export function CarePage() {
  const { account, masterKey } = useAuthVault(); const [prayers, setPrayers] = useState<PrayerRequestEntity[]>([]); const [followUps, setFollowUps] = useState<FollowUpEntity[]>([]); const [tasks, setTasks] = useState<TaskEntity[]>([]); const [rounds, setRounds] = useState<VisitRoundEntity[]>([]); const [visits, setVisits] = useState<VisitEntity[]>([]); const [families, setFamilies] = useState<FamilyEntity[]>([]); const [people, setPeople] = useState<PersonEntity[]>([]); const [churches, setChurches] = useState<ChurchEntity[]>([]); const [revealed, setRevealed] = useState<Set<string>>(new Set()); const [testimonies, setTestimonies] = useState<Record<string, string>>({}); const [taskTitle, setTaskTitle] = useState(''); const [taskDescription, setTaskDescription] = useState(''); const [taskDue, setTaskDue] = useState(''); const [taskPriority, setTaskPriority] = useState<'low' | 'normal' | 'high'>('normal'); const [taskChurch, setTaskChurch] = useState(''); const [roundName, setRoundName] = useState(''); const [roundChurch, setRoundChurch] = useState(''); const [roundFamilies, setRoundFamilies] = useState<Set<string>>(new Set()); const [error, setError] = useState('')
  const load = useCallback(async () => { if (!account || !masterKey) return; const district = await districts.getDistrict(account.id, masterKey); const [nextPrayers, nextFollowUps, nextTasks, nextRounds, nextFamilies, nextPeople, nextChurches, nextVisits] = await Promise.all([care.listPrayerRequests(account.id, masterKey), care.listFollowUps(account.id, masterKey), care.listTasks(account.id, masterKey), care.listRounds(account.id, masterKey), familiesService.listFamilies(account.id, masterKey), peopleService.listPeople(account.id, masterKey), district ? districts.listChurches(account.id, masterKey, district.id) : [], care.listVisits(account.id, masterKey)]); setPrayers(nextPrayers); setFollowUps(nextFollowUps); setTasks(nextTasks); setRounds(nextRounds); setFamilies(nextFamilies); setPeople(nextPeople); setChurches(nextChurches); setVisits(nextVisits) }, [account, masterKey])
  useReloadOnSync(load)
  const subjectName = (type: 'person' | 'family' | 'anonymous' | 'unregistered', id: string | null) => type === 'anonymous' ? 'Pedido sem identificação' : type === 'unregistered' ? 'Pessoa não cadastrada' : type === 'person' ? people.find((person) => person.id === id)?.name : families.find((family) => family.id === id)?.name
  async function updatePrayer(prayer: PrayerRequestEntity, status: PrayerRequestEntity['status']) { if (!account || !masterKey) return; await care.updatePrayer(account.id, masterKey, prayer, status, testimonies[prayer.id] ?? prayer.testimony); await load() }
  async function updateFollow(follow: FollowUpEntity) { if (!account || !masterKey) return; await care.updateFollowUp(account.id, masterKey, follow, follow.status === 'pending' ? 'completed' : 'pending'); await load() }
  async function updateTask(task: TaskEntity) { if (!account || !masterKey) return; await care.updateTask(account.id, masterKey, task, task.status === 'pending' ? 'completed' : 'pending'); await load() }
  async function createRound(event: FormEvent) { event.preventDefault(); if (!account || !masterKey) return; try { await care.createRound(account.id, masterKey, roundName, roundChurch || null, [...roundFamilies]); setRoundName(''); setRoundFamilies(new Set()); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível criar a rodada.') } }
  async function createTask(event: FormEvent) { event.preventDefault(); if (!account || !masterKey) return; try { await care.createTask(account.id, masterKey, { title: taskTitle, description: taskDescription, dueAt: taskDue, priority: taskPriority, churchId: taskChurch || null, relatedType: null, relatedId: null, reminderMinutes: null }); setTaskTitle(''); setTaskDescription(''); setTaskDue(''); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível criar a tarefa.') } }
  const now = new Date().toISOString().slice(0, 10)
  return <div className="page-stack"><header className="page-hero"><div><p className="eyebrow">Cuidados</p><h1>Pedidos, acompanhamentos e tarefas</h1><p>O painel revela apenas o necessário. Textos de oração começam ocultos.</p></div><Link className="button" to="/app/visitas/nova"><Plus />Nova visita</Link></header>{error && <div className="alert alert--error">{error}</div>}<section className="dashboard-metrics"><a href="#pedidos"><small>Pedidos ativos</small><strong>{prayers.filter(({ status }) => status === 'active').length}</strong><span>Revisão privada</span></a><a href="#acompanhamentos"><small>Acompanhamentos</small><strong>{followUps.filter(({ status }) => status === 'pending').length}</strong><span>Pendentes</span></a><a href="#tarefas"><small>Tarefas vencidas</small><strong>{tasks.filter(({ status, dueAt }) => status === 'pending' && dueAt < now).length}</strong><span>Sem alertas repetitivos</span></a><Link to="/app/visitas"><small>Pessoas visitadas</small><strong>{agruparVisitasPorIgreja(visits, churches).pessoasNoDistrito}</strong><span>No distrito</span></Link><a href="#rodadas"><small>Rodadas ativas</small><strong>{rounds.filter(({ status }) => status === 'active').length}</strong><span>Meta manual</span></a></section>
    <Card title="Pedidos de oração" eyebrow="Conteúdo oculto até tocar" id="pedidos">{!prayers.length ? <div className="empty-state compact-empty"><Heart /><strong>Nenhum pedido registrado</strong></div> : <div className="care-list">{prayers.map((prayer) => <article key={prayer.id}><div><strong>{subjectName(prayer.subjectType, prayer.subjectId) ?? 'Cadastro preservado'}</strong><small>Revisar em {new Intl.DateTimeFormat('pt-BR').format(new Date(`${prayer.reviewAt}T12:00`))} · {prayer.status}</small></div><p className={!revealed.has(prayer.id) ? 'sensitive-hidden' : ''}>{revealed.has(prayer.id) ? prayer.text : 'Conteúdo protegido'}</p>{revealed.has(prayer.id) && <label className="field"><span className="field__label">Testemunho ou resposta breve (opcional)</span><input className="field__input" value={testimonies[prayer.id] ?? prayer.testimony} onChange={(event) => setTestimonies((current) => ({ ...current, [prayer.id]: event.target.value }))} /></label>}<div className="care-actions"><Button variant="secondary" onClick={() => setRevealed((current) => { const next = new Set(current); if (next.has(prayer.id)) next.delete(prayer.id); else next.add(prayer.id); return next })} icon={revealed.has(prayer.id) ? <EyeOff /> : <Eye />}>{revealed.has(prayer.id) ? 'Ocultar' : 'Revelar'}</Button><label className="field compact-select"><span className="sr-only">Situação do pedido</span><select className="field__input" value={prayer.status} onChange={(event) => void updatePrayer(prayer, event.target.value as PrayerRequestEntity['status'])}><option value="active">Ativo</option><option value="answered">Respondido</option><option value="closed">Encerrado</option><option value="needs_follow_up">Acompanhamento necessário</option><option value="archived">Arquivado (legado)</option></select></label></div></article>)}</div>}</Card>
    <div className="home-grid"><Card title="Acompanhamentos" eyebrow="Pendentes e concluídos" id="acompanhamentos">{!followUps.length ? <div className="empty-state compact-empty"><RotateCcw /><strong>Nenhum acompanhamento</strong></div> : <div className="check-list">{followUps.map((follow) => <button key={follow.id} onClick={() => void updateFollow(follow)}>{follow.status === 'completed' ? <CheckCircle2 /> : <Circle />}<span><strong>{FOLLOW_UP_LABELS[follow.kind]}</strong><small>{subjectName(follow.subjectType, follow.subjectId)} · {follow.dueAt}</small></span></button>)}</div>}</Card><Card title="Tarefas" eyebrow="Prioridade sem excesso de alertas" id="tarefas"><form className="compact-task-form" onSubmit={(event) => void createTask(event)}><Field label="Nova tarefa" name="care-task-title" value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} required /><Field label="Prazo" name="care-task-due" type="date" value={taskDue} onChange={(event) => setTaskDue(event.target.value)} required /><label className="field"><span className="field__label">Prioridade</span><select className="field__input" value={taskPriority} onChange={(event) => setTaskPriority(event.target.value as typeof taskPriority)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option></select></label><label className="field"><span className="field__label">Igreja (opcional)</span><select className="field__input" value={taskChurch} onChange={(event) => setTaskChurch(event.target.value)}><option value="">Sem vínculo</option>{churches.map((church) => <option key={church.id} value={church.id}>{church.name}</option>)}</select></label><label className="field full-span"><span className="field__label">Descrição opcional</span><textarea className="field__input" rows={2} value={taskDescription} onChange={(event) => setTaskDescription(event.target.value)} /></label><Button type="submit" disabled={!taskTitle || !taskDue} icon={<Plus />}>Criar tarefa</Button></form>{!tasks.length ? <div className="empty-state compact-empty"><ListChecks /><strong>Nenhuma tarefa</strong></div> : <div className="check-list">{tasks.map((task) => <button key={task.id} className={task.status === 'pending' && task.dueAt < now ? 'overdue' : ''} onClick={() => void updateTask(task)}>{task.status === 'completed' ? <CheckCircle2 /> : <Circle />}<span><strong>{task.title}</strong><small>{task.dueAt} · prioridade {task.priority}</small></span></button>)}</div>}</Card></div>
    <Card title="Rodadas de visitação" eyebrow="Sem prazo fixo ou ranking" id="rodadas"><form className="round-form" onSubmit={(event) => void createRound(event)}><div className="form-grid"><Field label="Nome da rodada" name="round-name" value={roundName} onChange={(event) => setRoundName(event.target.value)} required /><label className="field"><span className="field__label">Igreja (opcional)</span><select className="field__input" value={roundChurch} onChange={(event) => setRoundChurch(event.target.value)}><option value="">Distrito inteiro</option>{churches.map((church) => <option key={church.id} value={church.id}>{church.name}</option>)}</select></label></div><div className="family-selector">{families.filter((family) => !roundChurch || family.primaryChurchId === roundChurch).map((family) => <label key={family.id}><input type="checkbox" checked={roundFamilies.has(family.id)} onChange={(event) => setRoundFamilies((current) => { const next = new Set(current); if (event.target.checked) next.add(family.id); else next.delete(family.id); return next })} />{family.name}</label>)}</div><Button type="submit" disabled={!roundName || !roundFamilies.size} icon={<UsersRound />}>Iniciar rodada</Button></form><div className="round-list">{rounds.map((round) => { const total = round.targetFamilyIds.length; const visited = round.visitedFamilyIds.length; return <article key={round.id} className={round.status === 'completed' ? 'round-complete' : ''}><span><strong>{round.name}</strong><small>{visited} de {total} famílias visitadas</small></span><progress value={visited} max={total} aria-label={`Progresso da ${round.name}`} /><span className="entity-badge">{round.status === 'completed' ? 'Concluída' : 'Ativa'}</span></article> })}</div></Card></div>
}
