import { useReloadOnSync } from '../sync/useReloadOnSync'
import { CalendarDays, Megaphone, Plus, TriangleAlert } from 'lucide-react'
import { useCallback, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuthVault } from '../auth/AuthVaultContext'
import { Card } from '../components/ui/Card'
import { DistrictService } from '../district/service'
import type { ChurchEntity } from '../district/types'
import { campaignDashboard, isTaskDueSoon, isTaskUrgent } from '../evangelism/core'
import { EvangelismPlanningService } from '../evangelism/service'
import { CAMPAIGN_STATUS_LABELS, type CampaignStatus, type EvangelismCampaignEntity } from '../evangelism/types'
import { rotuloDoTrimestre } from '../integrated-report/types'
import { anoDaCampanha, campanhasEmAndamento, fimDaCampanha, hojeLocal, periodoCurto, proximasCampanhas, ROTULOS_DA_SITUACAO, situacaoDaCampanha, textoDoPeriodo } from '../evangelism/periodo'

const service = new EvangelismPlanningService(); const districtService = new DistrictService()
export function EvangelismPage() {
  const { account, masterKey } = useAuthVault(); const [campaigns, setCampaigns] = useState<EvangelismCampaignEntity[]>([]); const [churches, setChurches] = useState<ChurchEntity[]>([]); const [churchId, setChurchId] = useState(''); const [year, setYear] = useState(new Date().getFullYear()); const [status, setStatus] = useState<CampaignStatus | ''>(''); const [error, setError] = useState('')
  const load = useCallback(async () => { if (!account || !masterKey) return; try { await service.consolidarCampanhasEMetas(account.id, masterKey).catch(() => null); const district = await districtService.getDistrict(account.id, masterKey); const [nextCampaigns, nextChurches] = await Promise.all([service.listCampaigns(account.id, masterKey), district ? districtService.listChurches(account.id, masterKey, district.id) : []]); setCampaigns(nextCampaigns); setChurches(nextChurches) } catch { setError('Não foi possível abrir as campanhas.') } }, [account, masterKey]); useReloadOnSync(load)
  // Campanha informada no Relatório Integrado pode não ter data ainda: ela pertence ao ano do relatório.
  const hoje = hojeLocal()
  const visible = campaigns.filter((campaign) => anoDaCampanha(campaign) === year && (!churchId || campaign.churchIds.includes(churchId)) && (!status || campaign.status === status)); const summary = campaignDashboard(campaigns.filter((campaign) => anoDaCampanha(campaign) === year)); const tasks = visible.flatMap((campaign) => campaign.tasks.map((task) => ({ task, campaign }))); const emAndamento = campanhasEmAndamento(visible, hoje); const upcoming = proximasCampanhas(visible, hoje).slice(0, 5)
  const aCompletar = campaigns.filter((campaign) => campaign.aCompletar)
  return <div className="page-stack evangelism-page"><header className="page-hero"><div><h1>Evangelismo</h1></div><Link className="button" to="/app/evangelismo/nova"><Plus />Nova campanha</Link></header>{error && <div className="alert alert--error">{error}</div>}
    <section className="dashboard-metrics" aria-label="Resumo das campanhas"><div><small>Em planejamento</small><strong>{summary.planning}</strong><span>campanhas</span></div><div><small>Em preparação</small><strong>{summary.preparing}</strong><span>organização ativa</span></div><div><small>Em andamento</small><strong>{campanhasEmAndamento(campaigns.filter((campaign) => anoDaCampanha(campaign) === year), hoje).length}</strong><span>agora</span></div><div><small>Concluídas</small><strong>{summary.completed}</strong><span>no ano</span></div></section>
    {aCompletar.length > 0 && <Card title="A completar" eyebrow="Do Relatório Integrado"><div className="entity-list">{aCompletar.map((campaign) => <Link className="entity-row entity-row--link entity-row--texto" to={`/app/evangelismo/${campaign.id}`} key={campaign.id}><span><strong>{campaign.name || 'Campanha'}</strong><small>{churches.find(({ id }) => id === campaign.origemRelatorio?.churchId)?.name ?? 'Igreja'}{campaign.origemRelatorio ? ` · ${rotuloDoTrimestre(campaign.origemRelatorio.trimestre)}` : ''}</small></span><span>Completar</span></Link>)}</div></Card>}
    <Card title="Filtrar campanhas"><div className="filter-bar"><label className="field"><span className="field__label">Igreja</span><select className="field__input" value={churchId} onChange={(event) => setChurchId(event.target.value)}><option value="">Todas as igrejas</option>{churches.map((church) => <option value={church.id} key={church.id}>{church.name}</option>)}</select></label><label className="field"><span className="field__label">Ano</span><select className="field__input" value={year} onChange={(event) => setYear(Number(event.target.value))}>{Array.from({ length: 7 }, (_, index) => new Date().getFullYear() - 2 + index).map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="field"><span className="field__label">Situação</span><select className="field__input" value={status} onChange={(event) => setStatus(event.target.value as CampaignStatus | '')}><option value="">Todas</option>{Object.entries(CAMPAIGN_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div></Card>
    <div className="evangelism-dashboard"><Card title="Campanhas"><div className="campaign-grid">{visible.map((campaign) => <Link className="campaign-card" to={`/app/evangelismo/${campaign.id}`} key={campaign.id}><span className={`entity-badge situacao--${situacaoDaCampanha(campaign, hoje)}`}>{ROTULOS_DA_SITUACAO[situacaoDaCampanha(campaign, hoje)]}</span><Megaphone /><h3>{campaign.name}</h3><p>{campaign.description || 'Campanha do distrito'}</p><small>{textoDoPeriodo(campaign)}</small><strong>{campaign.points.length} ponto(s) · {campaign.tasks.filter(({ status: taskStatus }) => taskStatus !== 'completed').length} tarefa(s) pendente(s)</strong></Link>)}{!visible.length && <div className="empty-state"><Megaphone /><strong>Nenhuma campanha encontrada</strong><p>Crie uma campanha ou revise os filtros.</p><Link className="button" to="/app/evangelismo/nova"><Plus />Nova campanha</Link></div>}</div></Card><aside><Card title="Em andamento agora" action={<Megaphone />}>{emAndamento.length ? <div className="planning-upcoming">{emAndamento.map((campaign) => <Link to={`/app/evangelismo/${campaign.id}`} key={campaign.id}><time>{periodoCurto(campaign.startDate, fimDaCampanha(campaign))}</time><span><strong>{campaign.name}</strong><small>{campaign.location || 'Local a confirmar'}</small></span></Link>)}</div> : <p className="muted">Nenhuma campanha em andamento.</p>}</Card><Card title="Próximos eventos" action={<CalendarDays />}>{upcoming.length ? <div className="planning-upcoming">{upcoming.map((campaign) => <Link to={`/app/evangelismo/${campaign.id}`} key={campaign.id}><time>{periodoCurto(campaign.startDate, fimDaCampanha(campaign))}</time><span><strong>{campaign.name}</strong><small>{campaign.location || 'Local a confirmar'}</small></span></Link>)}</div> : <p className="muted">Nenhuma campanha próxima.</p>}</Card><Card title="Tarefas que pedem atenção" action={<TriangleAlert />}>{tasks.filter(({ task }) => isTaskUrgent(task) || isTaskDueSoon(task)).slice(0, 6).map(({ task, campaign }) => <Link className="task-attention-row" to={`/app/evangelismo/${campaign.id}#tarefas`} key={task.id}><span><strong>{task.title}</strong><small>{campaign.name} · prazo {task.dueDate}</small></span><span className={`entity-badge priority--${task.priority}`}>{isTaskUrgent(task) ? 'Urgente' : 'Próxima'}</span></Link>)}{!tasks.some(({ task }) => isTaskUrgent(task) || isTaskDueSoon(task)) && <p className="muted">Nenhuma tarefa urgente ou próxima do prazo.</p>}</Card></aside></div>
  </div>
}
