import { useReloadOnSync } from '../sync/useReloadOnSync'
import { ArrowLeft, Church, Clock3, Pencil, Trash2, UsersRound } from 'lucide-react'
import { useCallback, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuthVault } from '../auth/AuthVaultContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { DistrictService } from '../district/service'
import { FamilyService } from '../families/service'
import type { FamilyEntity } from '../families/types'
import { PeopleService } from '../people/service'
import type { PersonEntity } from '../people/types'

const service = new FamilyService(); const peopleService = new PeopleService(); const districtService = new DistrictService()
export function FamilyDetailPage() {
  const { familyId = '' } = useParams<{ familyId: string }>(); const { account, masterKey } = useAuthVault(); const navigate = useNavigate(); const [family, setFamily] = useState<FamilyEntity | null>(null); const [people, setPeople] = useState<PersonEntity[]>([]); const [churchName, setChurchName] = useState(''); const [error, setError] = useState(''); const [confirmDelete, setConfirmDelete] = useState(false); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { if (!account || !masterKey) return; try { const next = await service.getFamily(account.id, masterKey, familyId); if (!next) throw new Error('Família não encontrada.'); setFamily(next); setPeople((await peopleService.listPeople(account.id, masterKey)).filter(({ id }) => next.memberIds.includes(id))); const district = await districtService.getDistrict(account.id, masterKey); const churches = district ? await districtService.listChurches(account.id, masterKey, district.id) : []; setChurchName(churches.find(({ id }) => id === next.primaryChurchId)?.name ?? 'Igreja') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível abrir a família.') } finally { setLoading(false) } }, [account, familyId, masterKey])
  useReloadOnSync(load); async function remove() { if (!account || !masterKey || !family) return; await service.deleteFamily(account.id, masterKey, family.id); await navigate('/app/familias', { replace: true }) }
  if (loading) return <div className="app-loading">Abrindo a família…</div>; if (!family) return <div className="alert alert--error">{error}</div>
  return <div className="page-stack"><Link className="text-link back-link" to="/app/familias"><ArrowLeft />Voltar às famílias</Link><header className="page-hero district-hero"><div><p className="eyebrow">Família</p><h1>{family.name}</h1><p>{family.memberIds.length} integrante(s) · pessoas de igrejas diferentes são permitidas.</p></div><div className="page-actions"><Link className="button button--secondary" to={`/app/familias/${family.id}/editar`}><Pencil />Editar</Link><Button variant="danger" icon={<Trash2 />} onClick={() => setConfirmDelete(true)}>Excluir</Button></div></header>{confirmDelete && <Card className="danger-card"><h2>Excluir esta família?</h2><p>As pessoas continuarão cadastradas. Somente a composição familiar será removida.</p><div className="form-actions"><Button variant="danger" onClick={() => void remove()}>Confirmar exclusão</Button><Button variant="secondary" onClick={() => setConfirmDelete(false)}>Cancelar</Button></div></Card>}<div className="church-detail-grid"><Card eyebrow="Organização" title="Igreja principal"><p className="detail-highlight"><Church />{churchName}</p><p className="muted">A igreja principal não restringe a origem dos integrantes.</p></Card><Card eyebrow="Endereço" title="Localização"><p>{family.address || 'Não informado'}</p></Card></div><Card eyebrow="Composição" title="Integrantes">{people.length === 0 ? <div className="empty-state"><UsersRound /><strong>Nenhum integrante</strong><span>Edite para adicionar pessoas.</span></div> : <div className="entity-list">{people.map((person) => <Link className="entity-row" key={person.id} to={`/app/pessoas/${person.id}`}><span className="avatar">{person.name[0]}</span><span><strong>{person.name}</strong><small>Abrir perfil</small></span></Link>)}</div>}</Card><Card eyebrow="Uso interno" title="Observações"><p className={family.notes ? 'preserved-text' : 'muted'}>{family.notes || 'Nenhuma observação.'}</p></Card><Card eyebrow="Histórico" title="Alterações"><ol className="history-list">{[...family.history].reverse().map((entry) => <li key={entry.id}><span className="history-list__marker"><Clock3 /></span><div><strong>{entry.event === 'created' ? 'Família criada' : entry.event === 'members_updated' ? 'Composição atualizada' : 'Dados atualizados'}</strong><small>{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(entry.at))}</small></div></li>)}</ol></Card></div>
}
