import { ArrowLeft, Save, Search } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuthVault } from '../auth/AuthVaultContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Field } from '../components/ui/Field'
import { DistrictService } from '../district/service'
import type { ChurchEntity } from '../district/types'
import { FamilyService } from '../families/service'
import { emptyFamilyInput, type FamilyInput } from '../families/types'
import { PeopleService } from '../people/service'
import type { PersonEntity } from '../people/types'
import { normalizePersonName } from '../people/validation'

const service = new FamilyService(); const peopleService = new PeopleService(); const districtService = new DistrictService()
export function FamilyFormPage() {
  const { familyId } = useParams<{ familyId: string }>(); const { account, masterKey } = useAuthVault(); const navigate = useNavigate(); const [input, setInput] = useState<FamilyInput>(emptyFamilyInput()); const [people, setPeople] = useState<PersonEntity[]>([]); const [churches, setChurches] = useState<ChurchEntity[]>([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { if (!account || !masterKey) return; try { const district = await districtService.getDistrict(account.id, masterKey); const nextChurches = district ? await districtService.listChurches(account.id, masterKey, district.id) : []; setChurches(nextChurches); setPeople(await peopleService.listPeople(account.id, masterKey)); if (familyId) { const family = await service.getFamily(account.id, masterKey, familyId); if (!family) throw new Error('Família não encontrada.'); setInput({ name: family.name, primaryChurchId: family.primaryChurchId, memberIds: family.memberIds, address: family.address, notes: family.notes }) } else if (nextChurches.length === 1) setInput((current) => ({ ...current, primaryChurchId: nextChurches[0]!.id })) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível abrir a família.') } finally { setLoading(false) } }, [account, familyId, masterKey])
  useEffect(() => { void load() }, [load]); const filtered = useMemo(() => people.filter(({ name }) => normalizePersonName(name).includes(normalizePersonName(query))), [people, query]); const churchName = (id: string) => churches.find((church) => church.id === id)?.name ?? 'Igreja'
  function toggle(id: string) { setInput((current) => ({ ...current, memberIds: current.memberIds.includes(id) ? current.memberIds.filter((personId) => personId !== id) : [...current.memberIds, id] })) }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!account || !masterKey) return; setBusy(true); setError(''); try { const family = familyId ? await service.updateFamily(account.id, masterKey, familyId, input) : await service.createFamily(account.id, masterKey, input); await navigate(`/app/familias/${family.id}`, { replace: true }) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar a família.') } finally { setBusy(false) } }
  if (loading) return <div className="app-loading">Abrindo família cifrada…</div>
  return <div className="page-stack page-narrow"><Link className="text-link back-link" to={familyId ? `/app/familias/${familyId}` : '/app/familias'}><ArrowLeft />Voltar</Link><header className="page-hero"><div><p className="eyebrow">Famílias</p><h1>{familyId ? 'Editar família' : 'Nova família'}</h1><p>Escolha pessoas já cadastradas; integrantes podem pertencer a igrejas diferentes.</p></div></header>{error && <div className="alert alert--error" role="alert">{error}</div>}<form className="church-form" onSubmit={(event) => void submit(event)}><Card eyebrow="Identificação" title="Dados da família"><div className="form-grid"><Field label="Nome da família *" name="family-name" value={input.name} onChange={(event) => setInput((current) => ({ ...current, name: event.target.value }))} /><label className="field"><span className="field__label">Igreja principal *</span><select className="field__input" value={input.primaryChurchId} onChange={(event) => setInput((current) => ({ ...current, primaryChurchId: event.target.value }))}><option value="">Selecione</option>{churches.map((church) => <option key={church.id} value={church.id}>{church.name}</option>)}</select><span className="field__hint">Somente para organização; não limita os integrantes.</span></label></div><label className="field"><span className="field__label">Endereço opcional</span><textarea className="field__input field__textarea" value={input.address} onChange={(event) => setInput((current) => ({ ...current, address: event.target.value }))} /></label></Card><Card eyebrow={`${input.memberIds.length} selecionado(s)`} title="Integrantes"><label className="field search-only"><span className="field__label">Pesquisar membros</span><span className="search-input"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} /></span></label><div className="member-picker">{filtered.map((person) => <label key={person.id} className={`member-option ${input.memberIds.includes(person.id) ? 'member-option--selected' : ''}`}><input type="checkbox" checked={input.memberIds.includes(person.id)} onChange={() => toggle(person.id)} /><span className="avatar">{person.name[0]}</span><span><strong>{person.name}</strong><small>{churchName(person.currentChurchId)}</small></span></label>)}</div></Card><Card eyebrow="Uso interno" title="Observações"><label className="field"><span className="field__label">Observações administrativas</span><textarea className="field__input field__textarea" value={input.notes} onChange={(event) => setInput((current) => ({ ...current, notes: event.target.value }))} /></label></Card><div className="form-actions form-actions--sticky"><Button type="submit" disabled={busy} icon={<Save />}>{busy ? 'Salvando…' : 'Salvar família'}</Button><Link className="button button--secondary" to={familyId ? `/app/familias/${familyId}` : '/app/familias'}>Cancelar</Link></div></form></div>
}
