import { ArrowLeft, CheckCircle2, FileSearch, FileUp, RotateCcw, ShieldCheck, TriangleAlert } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuthVault } from '../auth/AuthVaultContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { DistrictService } from '../district/service'
import type { ChurchEntity } from '../district/types'
import { extractPdfText, pdfHash, validatePdfFile } from '../imports/pdf'
import { parseMemberText } from '../imports/parsers'
import { ImportService } from '../imports/service'
import type { ImportBatchEntity, MemberImportPreview } from '../imports/types'
import { PeopleService } from '../people/service'
import type { PersonEntity } from '../people/types'

const imports = new ImportService(); const peopleService = new PeopleService(); const districtService = new DistrictService()
export function MemberImportPage() {
  const { account, masterKey } = useAuthVault(); const [people, setPeople] = useState<PersonEntity[]>([]); const [churches, setChurches] = useState<ChurchEntity[]>([]); const [batches, setBatches] = useState<ImportBatchEntity[]>([]); const [preview, setPreview] = useState<MemberImportPreview | null>(null); const [confirmed, setConfirmed] = useState(false); const [report, setReport] = useState<ImportBatchEntity | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { if (!account || !masterKey) return; const district = await districtService.getDistrict(account.id, masterKey); const [nextPeople, nextChurches, nextBatches] = await Promise.all([peopleService.listPeople(account.id, masterKey), district ? districtService.listChurches(account.id, masterKey, district.id) : [], imports.listBatches(account.id, masterKey, 'members')]); setPeople(nextPeople); setChurches(nextChurches); setBatches(nextBatches) }, [account, masterKey]); useEffect(() => { void load() }, [load])
  async function analyze(text: string, hash: string) { if (!account || !masterKey) return; setPreview(await imports.previewMembers(account.id, masterKey, hash, parseMemberText(text), people, churches)); setConfirmed(false); setReport(null) }
  async function selectFile(file: File | undefined) { if (!file) return; setBusy(true); setError(''); try { validatePdfFile(file); const bytes = await file.arrayBuffer(); const [hash, text] = await Promise.all([pdfHash(bytes), extractPdfText(bytes)]); await analyze(text, hash) } catch (reason) { setPreview(null); setError(reason instanceof Error ? reason.message : 'Não foi possível analisar o PDF.') } finally { setBusy(false) } }
  async function simulate() { setBusy(true); setError(''); try { const church = churches[0]; if (!church) throw new Error('Cadastre ao menos uma igreja antes de importar.'); const text = `IGREJA: ${church.name}\nPessoa Aurora Fictícia | 21/08/1990\nPessoa Horizonte Fictícia | 10/05/1985\nPessoa 123 Revisar | 01/01/1800`; await analyze(text, `simulated-members-${church.id}`) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível preparar a demonstração.') } finally { setBusy(false) } }
  async function apply() { if (!account || !masterKey || !preview || !confirmed) return; setBusy(true); setError(''); try { const result = await imports.applyPreview(account.id, masterKey, preview); setReport(result.batch); setPreview(null); setConfirmed(false); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível aplicar a importação.') } finally { setBusy(false) } }
  async function undo() { if (!account || !masterKey) return; setBusy(true); setError(''); try { await imports.undoLatest(account.id, masterKey, 'members'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível desfazer.') } finally { setBusy(false) } }
  return <div className="page-stack page-narrow"><Link className="text-link back-link" to="/app/pessoas"><ArrowLeft />Voltar às pessoas</Link><header className="page-hero"><div><p className="eyebrow">Importação</p><h1>Importar lista de membros</h1><p>O PDF é lido localmente, não é enviado e não fica armazenado depois da extração.</p></div><ShieldCheck /></header>{error && <div className="alert alert--error" role="alert">{error}</div>}<Card eyebrow="Etapa 1" title="Selecionar PDF"><label className="file-picker"><FileUp /><span><strong>{busy ? 'Lendo o PDF…' : 'Escolher lista de membros'}</strong><small>PDF textual, até 20 MB. Arquivos escaneados sem OCR serão recusados.</small></span><input type="file" accept="application/pdf,.pdf" disabled={busy} onChange={(event) => { void selectFile(event.target.files?.[0]); event.currentTarget.value = '' }} /></label><Button variant="secondary" onClick={() => void simulate()} disabled={busy} icon={<FileSearch />}>Usar importação fictícia simulada</Button></Card>
    {preview && <Card eyebrow="Etapa 2 · Prévia" title="Confira antes de salvar">{preview.alreadyImported && <div className="alert alert--success"><CheckCircle2 />Este PDF já foi aplicado. Zero pessoas novas serão criadas.</div>}<div className="import-metrics"><div><small>Encontradas</small><strong>{preview.parsedRows}</strong></div><div><small>Novas</small><strong>{preview.newPeople.length}</strong></div><div><small>Atualizadas</small><strong>{preview.updatedPeople.length}</strong></div><div><small>Possíveis ausentes</small><strong>{preview.missingPeople.length}</strong></div><div><small>Divergências</small><strong>{preview.issues.length}</strong></div></div><h3>Quantidade por igreja</h3><div className="breakdown-list">{Object.entries(preview.churchCounts).map(([name, count]) => <div key={name}><span>{name}</span><strong>{count}</strong></div>)}</div>{preview.issues.length > 0 && <div className="issue-list"><h3><TriangleAlert />Exigem atenção</h3>{preview.issues.map((item) => <div key={item.id}><strong>{item.displayName}</strong><span>{item.churchName} · {item.message}</span></div>)}</div>}{preview.missingPeople.length > 0 && <div className="issue-list missing-list"><h3>Membros ausentes da lista mais recente</h3>{preview.missingPeople.map((item) => <div key={item.personId}><strong>{item.nextData.name}</strong><span>Passará para “Não consta na lista atual”; a situação pastoral não será alterada.</span></div>)}</div>}<label className="confirmation-check"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /><span>Revisei a prévia e confirmo a aplicação das alterações válidas. Divergências não serão incluídas automaticamente.</span></label><Button disabled={!confirmed || busy || preview.alreadyImported} onClick={() => void apply()} icon={<CheckCircle2 />}>{busy ? 'Aplicando lote protegido…' : 'Confirmar e aplicar'}</Button></Card>}
    {report && <Card eyebrow="Relatório final" title="Importação concluída"><div className="alert alert--success"><CheckCircle2 />As alterações foram aplicadas em um único lote protegido.</div><div className="import-metrics"><div><small>Novas</small><strong>{report.summary.created}</strong></div><div><small>Atualizadas</small><strong>{report.summary.updated}</strong></div><div><small>Ausentes</small><strong>{report.summary.missing}</strong></div><div><small>Divergências</small><strong>{report.summary.issues}</strong></div></div></Card>}
    <Card eyebrow="Histórico" title="Importações de membros" action={batches.some(({ status }) => status === 'applied') ? <Button variant="secondary" disabled={busy} onClick={() => void undo()} icon={<RotateCcw />}>Desfazer última</Button> : null}>{batches.length === 0 ? <div className="empty-state compact-empty"><FileSearch /><strong>Nenhuma importação</strong></div> : <div className="import-history">{batches.map((batch) => <div key={batch.id}><span><strong>{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(batch.appliedAt))}</strong><small>{batch.status === 'applied' ? 'Aplicada' : 'Desfeita'} · {batch.summary.parsedRows} linhas</small></span><span>{batch.summary.issues} divergência(s)</span></div>)}</div>}</Card>
  </div>
}
