import { ArrowLeft, CheckCircle2, FileSearch, FileUp, RotateCcw, ShieldCheck, TriangleAlert } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuthVault } from '../auth/AuthVaultContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { DistrictService } from '../district/service'
import type { ChurchEntity } from '../district/types'
import { extractPdfText, pdfHash, validatePdfFile } from '../imports/pdf'
import { parseMemberText, parsePastedMemberList } from '../imports/parsers'
import { extractDocxText, validateDocxFile } from '../imports/docx'
import { ImportService } from '../imports/service'
import type { ImportBatchEntity, MemberImportPreview } from '../imports/types'
import { PeopleService } from '../people/service'
import type { PersonEntity } from '../people/types'

const imports = new ImportService()

/** Identifica a lista para a prévia reconhecer uma reaplicação, como no PDF. */
async function listHash(churchId: string, text: string): Promise<string> {
  const bytes = new TextEncoder().encode(`${churchId}:${text.trim()}`)
  const resumo = await crypto.subtle.digest('SHA-256', bytes)
  return [...new Uint8Array(resumo)].map((byte) => byte.toString(16).padStart(2, '0')).join('')
}; const peopleService = new PeopleService(); const districtService = new DistrictService()
/**
 * A importação vive dentro da igreja escolhida. Em modo embutido ela não
 * pergunta a igreja de novo nem repete o cabeçalho da página.
 */
export function MemberImportPage({ churchId = '', embedded = false }: { churchId?: string; embedded?: boolean } = {}) {
  const { account, masterKey } = useAuthVault(); const [people, setPeople] = useState<PersonEntity[]>([]); const [churches, setChurches] = useState<ChurchEntity[]>([]); const [batches, setBatches] = useState<ImportBatchEntity[]>([]); const [preview, setPreview] = useState<MemberImportPreview | null>(null); const [confirmed, setConfirmed] = useState(false); const [report, setReport] = useState<ImportBatchEntity | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [pasted, setPasted] = useState(''); const [listChurchId, setListChurchId] = useState(churchId)
  const load = useCallback(async () => { if (!account || !masterKey) return; const district = await districtService.getDistrict(account.id, masterKey); const [nextPeople, nextChurches, nextBatches] = await Promise.all([peopleService.listPeople(account.id, masterKey), district ? districtService.listChurches(account.id, masterKey, district.id) : [], imports.listBatches(account.id, masterKey, 'members')]); setPeople(nextPeople); setChurches(nextChurches); setBatches(nextBatches) }, [account, masterKey]); useEffect(() => { void load() }, [load])
  async function analyze(text: string, hash: string) { if (!account || !masterKey) return; setPreview(await imports.previewMembers(account.id, masterKey, hash, parseMemberText(text), people, churches)); setConfirmed(false); setReport(null) }
  // A lista colada e a do Word passam pela mesma prévia do PDF: nada é aplicado
  // sem o pastor conferir.
  async function analyzeList(text: string) {
    if (!account || !masterKey) return
    const igreja = churches.find(({ id }) => id === listChurchId)
    if (!igreja) throw new Error('Escolha a igreja desta lista antes de conferir.')
    const rows = parsePastedMemberList(text, igreja.name)
    const hash = await listHash(igreja.id, text)
    setPreview(await imports.previewMembers(account.id, masterKey, hash, rows, people, churches))
    setConfirmed(false); setReport(null)
  }
  async function reviewPasted() { setBusy(true); setError(''); try { await analyzeList(pasted) } catch (reason) { setPreview(null); setError(reason instanceof Error ? reason.message : 'Não foi possível ler a lista.') } finally { setBusy(false) } }
  async function selectDocx(file: File | undefined) { if (!file) return; setBusy(true); setError(''); try { validateDocxFile(file); const texto = await extractDocxText(await file.arrayBuffer()); setPasted(texto); await analyzeList(texto) } catch (reason) { setPreview(null); setError(reason instanceof Error ? reason.message : 'Não foi possível ler o arquivo do Word.') } finally { setBusy(false) } }
  async function selectFile(file: File | undefined) { if (!file) return; setBusy(true); setError(''); try { validatePdfFile(file); const bytes = await file.arrayBuffer(); const [hash, text] = await Promise.all([pdfHash(bytes), extractPdfText(bytes)]); await analyze(text, hash) } catch (reason) { setPreview(null); setError(reason instanceof Error ? reason.message : 'Não foi possível analisar o PDF.') } finally { setBusy(false) } }
  async function apply() { if (!account || !masterKey || !preview || !confirmed) return; setBusy(true); setError(''); try { const result = await imports.applyPreview(account.id, masterKey, preview); setReport(result.batch); setPreview(null); setConfirmed(false); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível aplicar a importação.') } finally { setBusy(false) } }
  async function undo() { if (!account || !masterKey) return; setBusy(true); setError(''); try { await imports.undoLatest(account.id, masterKey, 'members'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível desfazer.') } finally { setBusy(false) } }
  return <div className={embedded ? 'page-stack' : 'page-stack page-narrow'}>{!embedded && <><Link className="text-link back-link" to="/app/distrito"><ArrowLeft />Voltar ao distrito</Link><header className="page-hero"><div><p className="eyebrow">Importação</p><h1>Importar lista de membros</h1><p>O PDF é lido localmente, não é enviado e não fica armazenado depois da extração.</p></div><ShieldCheck /></header></>}{error && <div className="alert alert--error" role="alert">{error}</div>}<Card eyebrow="Etapa 1" title="Selecionar PDF"><label className="file-picker"><FileUp /><span><strong>{busy ? 'Lendo o PDF…' : 'Escolher lista de membros'}</strong><small>PDF textual, até 20 MB. Arquivos escaneados sem OCR serão recusados.</small></span><input type="file" accept="application/pdf,.pdf" disabled={busy} onChange={(event) => { void selectFile(event.target.files?.[0]); event.currentTarget.value = '' }} /></label></Card>
    <Card eyebrow="Etapa 1 · alternativa" title="Colar a lista ou enviar do Word"><p className="card-copy">Quando o PDF não é reconhecido, cole os nomes aqui — um por linha, com a data de nascimento quando houver. A conferência é a mesma.</p>{!churchId && <label className="field"><span className="field__label">Igreja desta lista</span><select className="field__input" value={listChurchId} onChange={(event) => setListChurchId(event.target.value)}><option value="">Selecione</option>{churches.map((church) => <option key={church.id} value={church.id}>{church.name}</option>)}</select></label>}<label className="field"><span className="field__label">Lista de membros</span><textarea className="field__input" rows={8} placeholder={'Ana Fictícia; 01/02/1990\nBruno Fictício 15/03/1985\nCarla Fictícia'} value={pasted} onChange={(event) => setPasted(event.target.value)} /><small className="field__hint">Aceita ponto e vírgula, vírgula, tabulação ou apenas espaço antes da data.</small></label><div className="form-actions"><Button onClick={() => void reviewPasted()} disabled={busy || !pasted.trim() || !listChurchId}>Conferir lista colada</Button><label className="file-picker"><FileUp /><span><strong>{busy ? 'Lendo o arquivo…' : 'Enviar arquivo do Word'}</strong><small>.docx até 8 MB, lido só neste aparelho.</small></span><input type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" disabled={busy || !listChurchId} onChange={(event) => { void selectDocx(event.target.files?.[0]); event.currentTarget.value = '' }} /></label></div></Card>
    {preview && <Card eyebrow="Etapa 2 · Prévia" title="Confira antes de salvar">{preview.alreadyImported && <div className="alert alert--success"><CheckCircle2 />Este PDF já foi aplicado. Zero pessoas novas serão criadas.</div>}<div className="import-metrics"><div><small>Encontradas</small><strong>{preview.parsedRows}</strong></div><div><small>Novas</small><strong>{preview.newPeople.length}</strong></div><div><small>Atualizadas</small><strong>{preview.updatedPeople.length}</strong></div><div><small>Possíveis ausentes</small><strong>{preview.missingPeople.length}</strong></div><div><small>Divergências</small><strong>{preview.issues.length}</strong></div></div><h3>Quantidade por igreja</h3><div className="breakdown-list">{Object.entries(preview.churchCounts).map(([name, count]) => <div key={name}><span>{name}</span><strong>{count}</strong></div>)}</div>{preview.issues.length > 0 && <div className="issue-list"><h3><TriangleAlert />Exigem atenção</h3>{preview.issues.map((item) => <div key={item.id}><strong>{item.displayName}</strong><span>{item.churchName} · {item.message}</span></div>)}</div>}{preview.missingPeople.length > 0 && <div className="issue-list missing-list"><h3>Membros ausentes da lista mais recente</h3>{preview.missingPeople.map((item) => <div key={item.personId}><strong>{item.nextData.name}</strong><span>Passará para “Não consta na lista atual”; a situação pastoral não será alterada.</span></div>)}</div>}<label className="confirmation-check"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /><span>Revisei a prévia e confirmo a aplicação das alterações válidas. Divergências não serão incluídas automaticamente.</span></label><Button disabled={!confirmed || busy || preview.alreadyImported} onClick={() => void apply()} icon={<CheckCircle2 />}>{busy ? 'Aplicando…' : 'Confirmar e aplicar'}</Button></Card>}
    {report && <Card eyebrow="Relatório final" title="Importação concluída"><div className="alert alert--success"><CheckCircle2 />As alterações foram aplicadas em um único lote protegido.</div><div className="import-metrics"><div><small>Novas</small><strong>{report.summary.created}</strong></div><div><small>Atualizadas</small><strong>{report.summary.updated}</strong></div><div><small>Ausentes</small><strong>{report.summary.missing}</strong></div><div><small>Divergências</small><strong>{report.summary.issues}</strong></div></div></Card>}
    <Card eyebrow="Histórico" title="Importações de membros" action={batches.some(({ status }) => status === 'applied') ? <Button variant="secondary" disabled={busy} onClick={() => void undo()} icon={<RotateCcw />}>Desfazer última</Button> : null}>{batches.length === 0 ? <div className="empty-state compact-empty"><FileSearch /><strong>Nenhuma importação</strong></div> : <div className="import-history">{batches.map((batch) => <div key={batch.id}><span><strong>{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(batch.appliedAt))}</strong><small>{batch.status === 'applied' ? 'Aplicada' : 'Desfeita'} · {batch.summary.parsedRows} linhas</small></span><span>{batch.summary.issues} divergência(s)</span></div>)}</div>}</Card>
  </div>
}
