import { BookHeart, CheckCircle2, Plus } from 'lucide-react'
import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { useAuthVault } from '../auth/AuthVaultContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Field } from '../components/ui/Field'
import { DistrictService } from '../district/service'
import type { ChurchEntity } from '../district/types'
import { MissionaryService } from '../missionary/service'
import { INTEREST_STATUS_LABELS, type BibleStudyEntity, type InterestEntity } from '../missionary/types'
const service = new MissionaryService(); const district = new DistrictService()
export function MissionaryPage() {
 const { account, masterKey } = useAuthVault(); const [churches,setChurches]=useState<ChurchEntity[]>([]); const [items,setItems]=useState<InterestEntity[]>([]); const [studies,setStudies]=useState<BibleStudyEntity[]>([]); const [churchId,setChurchId]=useState(''); const [name,setName]=useState(''); const [contact,setContact]=useState(''); const [notes,setNotes]=useState(''); const [error,setError]=useState('')
 const load=useCallback(async()=>{if(!account||!masterKey)return;try{const root=await district.getDistrict(account.id,masterKey);const [a,b,c]=await Promise.all([service.listInterests(account.id,masterKey),service.listStudies(account.id,masterKey),root?district.listChurches(account.id,masterKey,root.id):[]]);setItems(a);setStudies(b);setChurches(c)}catch{setError('Não foi possível abrir os dados missionários.')}},[account,masterKey]);useEffect(()=>{void load()},[load])
 async function create(event:FormEvent){event.preventDefault();if(!account||!masterKey)return;try{await service.saveInterest(account.id,masterKey,{churchId,name,contact,notes,status:'waiting_study'});setName('');setContact('');setNotes('');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível cadastrar.')}}
 async function start(item:InterestEntity){if(!account||!masterKey)return;await service.startStudy(account.id,masterKey,item,new Date().toISOString());await load()} async function finish(study:BibleStudyEntity){if(!account||!masterKey)return;const item=items.find(value=>value.id===study.interestId);if(!item)return;await service.completeStudy(account.id,masterKey,study,item,'continue_interested','');await load()}
 const month=new Date().toISOString().slice(0,7);const year=String(new Date().getFullYear()); const churchName=(id:string)=>churches.find(church=>church.id===id)?.name??'Igreja não encontrada'
 return <div className="page-stack"><header className="page-hero"><div><p className="eyebrow">Missionário</p><h1>Interessados e estudos bíblicos</h1><p>Cadastros e acompanhamentos, disponíveis sem internet.</p></div><BookHeart/></header>{error&&<div className="alert alert--error">{error}</div>}<section className="dashboard-metrics"><div><small>Interessados</small><strong>{items.length}</strong><span>no aplicativo local</span></div><div><small>Estudos no mês</small><strong>{studies.filter(item=>item.startedAt.startsWith(month)).length}</strong><span>iniciados</span></div><div><small>Estudos no ano</small><strong>{studies.filter(item=>item.startedAt.startsWith(year)).length}</strong><span>acumulado</span></div></section><Card title="Novo interessado" eyebrow="Igreja obrigatória"><form className="compact-task-form" onSubmit={event=>void create(event)}><label className="field"><span className="field__label">Igreja</span><select className="field__input" required value={churchId} onChange={event=>setChurchId(event.target.value)}><option value="">Selecionar</option>{churches.map(church=><option key={church.id} value={church.id}>{church.name}</option>)}</select></label><Field label="Nome" name="interest-name" value={name} onChange={event=>setName(event.target.value)} required/><Field label="Contato (opcional)" name="interest-contact" value={contact} onChange={event=>setContact(event.target.value)}/><label className="field"><span className="field__label">Observações privadas</span><textarea className="field__input" value={notes} onChange={event=>setNotes(event.target.value)}/></label><Button type="submit" disabled={!churchId||!name.trim()} icon={<Plus/>}>Cadastrar interessado</Button></form></Card><Card title="Histórico e acompanhamento" eyebrow="Por pessoa e igreja">{items.length===0?<div className="empty-state compact-empty"><BookHeart/><strong>Nenhum interessado cadastrado</strong><span>Cadastre um interessado para iniciar o acompanhamento.</span></div>:<div className="entity-list">{items.map(item=>{const study=studies.find(value=>value.interestId===item.id&&value.status==='in_progress');return <div className="entity-row" key={item.id}><span className="avatar"><BookHeart/></span><span><strong>{item.name}</strong><small>{churchName(item.churchId)} · {INTEREST_STATUS_LABELS[item.status]}</small></span>{item.status==='waiting_study'?<Button variant="secondary" onClick={()=>void start(item)}>Iniciar estudo</Button>:study?<Button variant="secondary" icon={<CheckCircle2/>} onClick={()=>void finish(study)}>Concluir</Button>:null}</div>})}</div>}</Card></div>
}
