import { useReloadOnSync } from '../sync/useReloadOnSync'
import { ClipboardCheck, Plus } from 'lucide-react'
import { useCallback, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuthVault } from '../auth/AuthVaultContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { DistrictService } from '../district/service'
import type { ChurchEntity } from '../district/types'
import { processMetrics } from '../nominations/core'
import { NominationService } from '../nominations/service'
import type { NominationProcessEntity, NominationStatus } from '../nominations/types'

const service = new NominationService(); const districts = new DistrictService()
const statusLabels: Record<NominationStatus, string> = { preparation: 'Preparação', formed: 'Comissão formada', nominating: 'Indicações em andamento', awaiting_consent: 'Aguardando consentimentos', ready: 'Pronto para apresentar', presented: 'Apresentado à igreja', objections: 'Em revisão por objeções', voting: 'Em votação', completed: 'Concluído', archived: 'Arquivado' }

export function NominationProcessesPage() {
  const { account, masterKey } = useAuthVault(); const navigate = useNavigate()
  const [churches, setChurches] = useState<ChurchEntity[]>([]); const [churchId, setChurchId] = useState(''); const [processes, setProcesses] = useState<NominationProcessEntity[]>([]); const [period, setPeriod] = useState(`Nomeações ${new Date().getFullYear() + 1}`); const [creating, setCreating] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { if (!account || !masterKey) return; const district = await districts.getDistrict(account.id, masterKey); const next = district ? await districts.listChurches(account.id, masterKey, district.id) : []; setChurches(next); const selected = churchId || next[0]?.id || ''; setChurchId(selected); setProcesses(await service.list(account.id, masterKey, selected)) }, [account, masterKey, churchId])
  useReloadOnSync(load)
  async function create() { if (!account || !masterKey || !churchId) return; try { const process = await service.create(account.id, masterKey, churchId, period); void navigate(`/app/comissoes/nomeacoes/${process.id}`) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível criar o processo.') } }
  const allMetrics = processes.reduce((total, process) => { const metrics = processMetrics(process); total.vacant += metrics.vacant; total.consent += metrics.awaitingConsent; total.objections += metrics.objections; return total }, { vacant: 0, consent: 0, objections: 0 })
  return <div className="page-stack"><Link className="text-link back-link" to="/app/comissoes">Voltar a Comissões</Link><header className="page-hero"><div><p className="eyebrow">Organização da igreja</p><h1>Comissão de Nomeações</h1></div><Button icon={<Plus />} onClick={() => setCreating(true)}>Novo processo</Button></header>{error && <div className="alert alert--error" role="alert">{error}</div>}<label className="field"><span className="field__label">Igreja</span><select className="field__input" value={churchId} onChange={(event) => setChurchId(event.target.value)}>{churches.map((church) => <option key={church.id} value={church.id}>{church.name}</option>)}</select></label><section className="dashboard-metrics"><div><small>Processos em andamento</small><strong>{processes.filter((process) => !['completed', 'archived'].includes(process.status)).length}</strong></div><div><small>Aguardando consentimento</small><strong>{allMetrics.consent}</strong></div><div><small>Prontos para apresentar</small><strong>{processes.filter((process) => process.status === 'ready').length}</strong></div><div><small>Com objeções</small><strong>{allMetrics.objections}</strong></div><div><small>Concluídos</small><strong>{processes.filter((process) => process.status === 'completed').length}</strong></div><div><small>Vagas abertas</small><strong>{allMetrics.vacant}</strong></div></section>{creating && <Card title="Novo processo de nomeações"><label className="field"><span className="field__label">Período</span><input className="field__input" value={period} onChange={(event) => setPeriod(event.target.value)} /></label><div className="form-actions"><Button onClick={() => void create()}>Criar processo</Button><Button variant="secondary" onClick={() => setCreating(false)}>Cancelar</Button></div></Card>}<Card title="Processos da igreja">{processes.length ? <div className="entity-list">{processes.map((process) => { const metrics = processMetrics(process); return <Link className="entity-row entity-row--link" to={`/app/comissoes/nomeacoes/${process.id}`} key={process.id}><span><strong>{process.period}</strong><small>{statusLabels[process.status]} · {metrics.filled} cargo(s) preenchido(s) · {metrics.vacant} vaga(s)</small></span><span>Abrir</span></Link> })}</div> : <div className="empty-state"><ClipboardCheck /><strong>Nenhum processo de nomeações</strong><p>Crie um processo para esta igreja e período.</p></div>}</Card></div>
}
