import { ArrowLeft, Save } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuthVault } from '../auth/AuthVaultContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Field } from '../components/ui/Field'
import { DistrictService } from '../district/service'
import type { ChurchEntity } from '../district/types'
import { calculateAge } from '../people/dates'
import { PeopleService } from '../people/service'
import { emptyPersonInput, PASTORAL_STATUS_LABELS, type PastoralStatus, type PersonInput } from '../people/types'
import { PersonValidationError, type PersonFieldErrors, validatePersonInput } from '../people/validation'

const service = new PeopleService(); const districtService = new DistrictService()
export function PersonFormPage() {
  const { personId } = useParams<{ personId: string }>(); const { account, masterKey } = useAuthVault(); const navigate = useNavigate(); const [input, setInput] = useState<PersonInput>(emptyPersonInput()); const [churches, setChurches] = useState<ChurchEntity[]>([]); const [errors, setErrors] = useState<PersonFieldErrors>({}); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { if (!account || !masterKey) return; try { const district = await districtService.getDistrict(account.id, masterKey); const nextChurches = district ? await districtService.listChurches(account.id, masterKey, district.id) : []; setChurches(nextChurches); if (personId) { const person = await service.getPerson(account.id, masterKey, personId); if (!person) throw new Error('Pessoa não encontrada.'); setInput({ name: person.name, birthDate: person.birthDate ?? '', whatsapp: person.whatsapp, notes: person.notes, pastoralStatus: person.pastoralStatus, currentChurchId: person.currentChurchId }) } else if (nextChurches.length === 1) setInput((current) => ({ ...current, currentChurchId: nextChurches[0]!.id })) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível abrir o cadastro.') } finally { setLoading(false) } }, [account, masterKey, personId])
  useEffect(() => { void load() }, [load])
  function update<K extends keyof PersonInput>(field: K, value: PersonInput[K]) { setInput((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: '' })) }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!account || !masterKey) return; const validation = validatePersonInput(input); setErrors(validation); if (Object.keys(validation).length) { setError('Revise os campos destacados.'); return } setBusy(true); setError(''); try { const person = personId ? await service.updatePerson(account.id, masterKey, personId, input) : await service.createPerson(account.id, masterKey, input); await navigate(`/app/pessoas/${person.id}`, { replace: true }) } catch (reason) { if (reason instanceof PersonValidationError) setErrors(reason.fieldErrors); setError(reason instanceof Error ? reason.message : 'Não foi possível salvar a pessoa.') } finally { setBusy(false) } }
  if (loading) return <div className="app-loading" role="status">Abrindo cadastro protegido…</div>
  return <div className="page-stack page-narrow"><Link className="text-link back-link" to={personId ? `/app/pessoas/${personId}` : '/app/pessoas'}><ArrowLeft />Voltar</Link><header className="page-hero"><div><p className="eyebrow">Pessoas</p><h1>{personId ? 'Editar pessoa' : 'Nova pessoa'}</h1><p>A idade é calculada automaticamente. Nascimento, contato e observações ficam protegidos.</p></div></header>{error && <div className="alert alert--error" role="alert">{error}</div>}
    <form className="church-form" onSubmit={(event) => void submit(event)} noValidate><Card eyebrow="Identificação" title="Dados da pessoa"><div className="form-grid"><Field label="Nome completo *" name="person-name" value={input.name} onChange={(event) => update('name', event.target.value)} error={errors.name} maxLength={180} autoFocus /><Field label="Data de nascimento" name="birth-date" type="date" value={input.birthDate} onChange={(event) => update('birthDate', event.target.value)} error={errors.birthDate} hint={input.birthDate ? `Idade atual: ${calculateAge(input.birthDate) ?? '—'} anos` : 'Opcional'} /><label className="field"><span className="field__label">Igreja *</span><select className="field__input" value={input.currentChurchId} onChange={(event) => update('currentChurchId', event.target.value)} aria-invalid={Boolean(errors.currentChurchId)}><option value="">Selecione</option>{churches.map((church) => <option value={church.id} key={church.id}>{church.name}</option>)}</select>{errors.currentChurchId && <span className="field__error">{errors.currentChurchId}</span>}</label><label className="field"><span className="field__label">Situação pastoral *</span><select className="field__input" value={input.pastoralStatus} onChange={(event) => update('pastoralStatus', event.target.value as PastoralStatus)}>{Object.entries(PASTORAL_STATUS_LABELS).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><Field label="WhatsApp" name="whatsapp" inputMode="tel" value={input.whatsapp} onChange={(event) => update('whatsapp', event.target.value)} error={errors.whatsapp} placeholder="DDD + número" /></div></Card><Card eyebrow="Uso interno" title="Observações opcionais"><label className="field"><span className="field__label">Observações administrativas</span><textarea className="field__input field__textarea field__textarea--large" value={input.notes} onChange={(event) => update('notes', event.target.value)} maxLength={2000} aria-invalid={Boolean(errors.notes)} />{errors.notes && <span className="field__error">{errors.notes}</span>}</label></Card><div className="form-actions form-actions--sticky"><Button type="submit" disabled={busy} icon={<Save />}>{busy ? 'Salvando no aplicativo…' : 'Salvar pessoa'}</Button><Link className="button button--secondary" to={personId ? `/app/pessoas/${personId}` : '/app/pessoas'}>Cancelar</Link></div></form>
  </div>
}
