/* eslint-disable @typescript-eslint/no-misused-promises */
import { BookCheck, BookOpen, Clock3, Goal, Pencil, Plus, Trash2 } from 'lucide-react'
import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { useAuthVault } from '../auth/AuthVaultContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Field } from '../components/ui/Field'
import { bookProgress, readingMonth, readingSummary } from '../reading/core'
import { ReadingService } from '../reading/service'
import { BOOK_CATEGORIES, BOOK_CATEGORY_LABELS, BOOK_STATUSES, BOOK_STATUS_LABELS, type BookCategory, type BookStatus, type ReadingBookData, type ReadingEntity, type ReadingGoalData, type ReadingSessionData } from '../reading/types'

const service = new ReadingService(); const timestamp = () => new Date().toISOString(); const today = () => new Date().toISOString().slice(0, 10)
const emptyBook = (): ReadingBookData => ({ title: '', author: '', category: 'theology', totalPages: null, pagesRead: 0, startDate: today(), completedDate: null, status: 'want_to_read', notes: '', createdAt: timestamp(), updatedAt: timestamp() })
type ReadingView = 'all' | 'want_to_read' | 'reading' | 'completed' | 'history' | 'goals'
const VIEW_LABELS: Record<ReadingView, string> = { all: 'Todos os livros', want_to_read: 'Quero ler', reading: 'Lendo', completed: 'Concluídos', history: 'Histórico de leituras', goals: 'Metas' }

export function ReadingPage() {
  const { account, masterKey } = useAuthVault(); const month = readingMonth(new Date())
  const [books, setBooks] = useState<ReadingEntity<ReadingBookData>[]>([]); const [sessions, setSessions] = useState<ReadingEntity<ReadingSessionData>[]>([]); const [goals, setGoals] = useState<ReadingEntity<ReadingGoalData>[]>([])
  const [view, setView] = useState<ReadingView>('all'); const [bookDraft, setBookDraft] = useState<ReadingBookData | null>(null); const [bookId, setBookId] = useState('')
  const [sessionOpen, setSessionOpen] = useState(false); const [sessionBookId, setSessionBookId] = useState(''); const [sessionDate, setSessionDate] = useState(today()); const [sessionPages, setSessionPages] = useState(0); const [sessionMinutes, setSessionMinutes] = useState(0); const [sessionNotes, setSessionNotes] = useState('')
  const currentGoal = goals.find((goal) => goal.month === month) ?? null; const [goalBooks, setGoalBooks] = useState(0); const [goalPages, setGoalPages] = useState(0); const [goalMinutes, setGoalMinutes] = useState(0)
  const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { if (!account || !masterKey) return; const [nextBooks, nextSessions, nextGoals] = await Promise.all([service.books(account.id, masterKey), service.sessions(account.id, masterKey), service.goals(account.id, masterKey)]); setBooks(nextBooks); setSessions(nextSessions); setGoals(nextGoals); const goal = nextGoals.find((item) => item.month === month); setGoalBooks(goal?.books ?? 0); setGoalPages(goal?.pages ?? 0); setGoalMinutes(goal?.minutes ?? 0) }, [account, masterKey, month, setGoalBooks, setGoalPages, setGoalMinutes])
  useEffect(() => { void load() }, [load])
  const summary = readingSummary(books, sessions, currentGoal, month)
  const visibleBooks = useMemo(() => view === 'all' ? books : ['want_to_read', 'reading', 'completed'].includes(view) ? books.filter(({ status }) => status === view) : [], [books, view])
  const monthSessions = sessions.filter(({ date }) => readingMonth(date) === month)
  const bookName = (id: string) => books.find((book) => book.id === id)?.title ?? 'Livro removido'
  async function saveBook(event: FormEvent) { event.preventDefault(); if (!account || !masterKey || !bookDraft) return; setBusy(true); setError(''); try { await service.saveBook(account.id, masterKey, bookDraft, bookId || undefined); setBookDraft(null); setBookId(''); setNotice('Livro salvo.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar o livro.') } finally { setBusy(false) } }
  async function saveSession(event: FormEvent) { event.preventDefault(); if (!account || !masterKey) return; setBusy(true); setError(''); try { await service.addSession(account.id, masterKey, { bookId: sessionBookId, date: sessionDate, pages: sessionPages, minutes: sessionMinutes, notes: sessionNotes }); setSessionOpen(false); setSessionBookId(''); setSessionPages(0); setSessionMinutes(0); setSessionNotes(''); setNotice('Leitura registrada.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível registrar a leitura.') } finally { setBusy(false) } }
  async function complete(book: ReadingEntity<ReadingBookData>) { if (!account || !masterKey) return; try { await service.completeBook(account.id, masterKey, book, today()); setNotice('Livro marcado como concluído.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível concluir o livro.') } }
  async function remove(book: ReadingEntity<ReadingBookData>) { if (!account || !masterKey || !window.confirm('Deseja excluir este livro e seu histórico de leituras?')) return; try { await service.removeBook(account.id, masterKey, book.id); setNotice('Livro excluído.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível excluir o livro.') } }
  async function saveGoal() { if (!account || !masterKey) return; try { const now = timestamp(); await service.saveGoal(account.id, masterKey, { month, books: goalBooks, pages: goalPages, minutes: goalMinutes, createdAt: currentGoal?.createdAt ?? now, updatedAt: now }); setNotice('Meta mensal salva.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar a meta.') } }

  return <div className="page-stack reading-page"><header className="page-hero"><div><p className="eyebrow">Área pessoal</p><h1>Leitura</h1><p>Acompanhe livros, páginas e tempo de leitura de forma simples e particular.</p></div><div className="page-actions"><Button variant="secondary" icon={<Clock3 />} onClick={() => setSessionOpen(true)}>Registrar leitura</Button><Button icon={<Plus />} onClick={() => { setBookId(''); setBookDraft(emptyBook()) }}>Adicionar livro</Button></div></header>
    {notice && <div className="alert alert--success" role="status">{notice}</div>}{error && <div className="alert alert--error" role="alert">{error}</div>}
    <section className="reading-metrics" aria-label="Resumo de leitura"><div><span>Em andamento</span><strong>{summary.reading}</strong></div><div><span>Concluídos no mês</span><strong>{summary.booksCompletedMonth}</strong></div><div><span>Concluídos no ano</span><strong>{summary.booksCompletedYear}</strong></div><div><span>Páginas no mês</span><strong>{summary.pages}</strong></div><div><span>Tempo no mês</span><strong>{Math.floor(summary.minutes / 60)}h {summary.minutes % 60}min</strong></div></section>
    <Card title="Meta mensal" eyebrow={new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(new Date())}><div className="reading-goal-summary"><span>Livros<strong>{summary.booksCompletedMonth} de {summary.goalBooks || '—'}</strong><progress max={summary.goalBooks || 1} value={summary.booksCompletedMonth} /></span><span>Páginas<strong>{summary.pages} de {summary.goalPages || '—'}</strong><progress max={summary.goalPages || 1} value={summary.pages} /></span><span>Minutos<strong>{summary.minutes} de {summary.goalMinutes || '—'}</strong><progress max={summary.goalMinutes || 1} value={summary.minutes} /></span></div><Button variant="quiet" onClick={() => setView('goals')}>Definir meta</Button></Card>
    <nav className="reading-nav" aria-label="Filtros de leitura">{(Object.keys(VIEW_LABELS) as ReadingView[]).map((item) => <button key={item} className={view === item ? 'active' : ''} aria-pressed={view === item} onClick={() => setView(item)}>{VIEW_LABELS[item]}</button>)}</nav>
    {bookDraft && <Card title={bookId ? 'Editar livro' : 'Adicionar livro'}><form onSubmit={saveBook}><div className="form-grid"><Field label="Título" name="reading-title" value={bookDraft.title} onChange={(event) => setBookDraft({ ...bookDraft, title: event.target.value })} required /><Field label="Autor" name="reading-author" value={bookDraft.author} onChange={(event) => setBookDraft({ ...bookDraft, author: event.target.value })} required /><label className="field"><span className="field__label">Categoria</span><select className="field__input" value={bookDraft.category} onChange={(event) => setBookDraft({ ...bookDraft, category: event.target.value as BookCategory })}>{BOOK_CATEGORIES.map((category) => <option key={category} value={category}>{BOOK_CATEGORY_LABELS[category]}</option>)}</select></label><Field label="Total de páginas (opcional)" name="reading-total-pages" type="number" min={1} value={bookDraft.totalPages ?? ''} onChange={(event) => setBookDraft({ ...bookDraft, totalPages: event.target.value ? Number(event.target.value) : null })} /><Field label="Data de início" name="reading-start" type="date" value={bookDraft.startDate} onChange={(event) => setBookDraft({ ...bookDraft, startDate: event.target.value })} /><label className="field"><span className="field__label">Situação</span><select className="field__input" value={bookDraft.status} onChange={(event) => setBookDraft({ ...bookDraft, status: event.target.value as BookStatus })}>{BOOK_STATUSES.map((status) => <option key={status} value={status}>{BOOK_STATUS_LABELS[status]}</option>)}</select></label></div><label className="field"><span className="field__label">Observação pessoal (opcional)</span><textarea className="field__input" rows={3} value={bookDraft.notes} onChange={(event) => setBookDraft({ ...bookDraft, notes: event.target.value })} /></label><div className="form-actions"><Button type="submit" disabled={busy}>{busy ? 'Salvando…' : 'Salvar livro'}</Button><Button type="button" variant="secondary" onClick={() => setBookDraft(null)}>Cancelar</Button></div></form></Card>}
    {sessionOpen && <Card title="Registrar leitura"><form onSubmit={saveSession}><div className="form-grid"><label className="field"><span className="field__label">Livro</span><select className="field__input" value={sessionBookId} onChange={(event) => setSessionBookId(event.target.value)} required><option value="">Selecione o livro</option>{books.filter(({ status }) => status !== 'completed').map((book) => <option value={book.id} key={book.id}>{book.title}</option>)}</select></label><Field label="Data" name="reading-session-date" type="date" value={sessionDate} onChange={(event) => setSessionDate(event.target.value)} required /><Field label="Páginas lidas" name="reading-session-pages" type="number" min={0} value={sessionPages || ''} onChange={(event) => setSessionPages(Number(event.target.value))} /><Field label="Tempo de leitura (minutos)" name="reading-session-minutes" type="number" min={0} value={sessionMinutes || ''} onChange={(event) => setSessionMinutes(Number(event.target.value))} /></div><label className="field"><span className="field__label">Observação (opcional)</span><textarea className="field__input" rows={3} value={sessionNotes} onChange={(event) => setSessionNotes(event.target.value)} /></label><div className="form-actions"><Button type="submit" disabled={busy}>{busy ? 'Salvando…' : 'Salvar leitura'}</Button><Button type="button" variant="secondary" onClick={() => setSessionOpen(false)}>Cancelar</Button></div></form></Card>}
    {view === 'history' ? <Card title="Histórico de leituras">{!monthSessions.length ? <div className="empty-state"><Clock3 /><strong>Nenhuma leitura registrada neste mês</strong></div> : <div className="reading-history">{monthSessions.map((session) => <article key={session.id}><span><strong>{bookName(session.bookId)}</strong><small>{new Intl.DateTimeFormat('pt-BR').format(new Date(`${session.date}T12:00:00`))}</small></span><span>{session.pages} página(s) · {session.minutes} minuto(s)</span>{session.notes && <p>{session.notes}</p>}</article>)}</div>}</Card> : view === 'goals' ? <Card title="Metas de leitura" eyebrow="Mês atual"><p className="muted">Você pode definir uma ou combinar as três metas.</p><div className="form-grid"><Field label="Livros concluídos" name="reading-goal-books" type="number" min={0} value={goalBooks || ''} onChange={(event) => setGoalBooks(Number(event.target.value))} /><Field label="Páginas lidas" name="reading-goal-pages" type="number" min={0} value={goalPages || ''} onChange={(event) => setGoalPages(Number(event.target.value))} /><Field label="Minutos de leitura" name="reading-goal-minutes" type="number" min={0} value={goalMinutes || ''} onChange={(event) => setGoalMinutes(Number(event.target.value))} /></div><Button icon={<Goal />} onClick={saveGoal}>Salvar meta mensal</Button></Card> : <section className="reading-grid">{!visibleBooks.length ? <Card className="reading-empty"><BookOpen /><h2>Nenhum livro nesta lista</h2><p>Adicione um livro para começar seu acompanhamento pessoal.</p><Button icon={<Plus />} onClick={() => setBookDraft(emptyBook())}>Adicionar livro</Button></Card> : visibleBooks.map((book) => { const progress = bookProgress(book); return <Card key={book.id} title={book.title} eyebrow={`${BOOK_CATEGORY_LABELS[book.category]} · ${BOOK_STATUS_LABELS[book.status]}`}><p className="muted">{book.author}</p><div className="reading-progress"><strong>{book.pagesRead} página(s) lida(s){book.totalPages ? ` de ${book.totalPages}` : ''}</strong>{progress !== null && <><progress max={100} value={progress} /><small>{progress}% concluído</small></>}</div>{book.notes && <p>{book.notes}</p>}<div className="form-actions">{book.status !== 'completed' && <Button variant="secondary" icon={<BookCheck />} onClick={() => complete(book)}>Marcar como concluído</Button>}<Button variant="quiet" icon={<Pencil />} onClick={() => { const { id, ...data } = book; setBookId(id); setBookDraft(data) }}>Editar</Button><Button variant="danger" icon={<Trash2 />} aria-label={`Excluir livro ${book.title}`} onClick={() => remove(book)} /></div></Card> })}</section>}
  </div>
}
