import { currentDeviceId } from '../auth/device'; import { decryptPayload, encryptPayload } from '../crypto/vault'; import { db, type ApoioDatabase } from '../db/database'; import { VaultRepository } from '../db/repository'; import type { GoalData, GoalEntity, GoalEntryData, GoalEntryEntity, GoalHistoryData, GoalHistoryEntity, GoalImportPreview, GoalMetric } from './types'
type GoalRecordType = 'goal' | 'goal_entry' | 'goal_history'
export function parseGoalsPdf(text: string, hash: string): GoalImportPreview { const entries: GoalImportPreview['entries'] = []; const errors: string[] = []; for (const line of text.split('\n')) { const parts = line.split('|').map((value) => value.trim()); if (parts.length !== 5) continue; const [churchId = '', date = '', rawMetric = '', rawAmount = '', reference = ''] = parts; if (!['tithes_offerings', 'baptisms', 'rebaptisms', 'professions_faith'].includes(rawMetric) || !/^\d{4}-\d{2}-\d{2}$/u.test(date) || !Number.isFinite(Number(rawAmount))) { errors.push('Linha com formato inválido.'); continue } entries.push({ churchId, date, metric: rawMetric as GoalMetric, amount: Number(rawAmount), reference }) } if (!entries.length && !errors.length) errors.push('Formato não reconhecido. Use linhas: igreja|AAAA-MM-DD|métrica|quantidade|referência.'); return { hash, entries, errors } }
export class GoalsService { private readonly repo: VaultRepository; constructor(private readonly database: ApoioDatabase = db) { this.repo = new VaultRepository(database) } private async list<T>(accountId: string, key: CryptoKey, recordType: GoalRecordType): Promise<T[]> { const values: Array<T | null> = await Promise.all((await this.repo.list(accountId, recordType)).map(async (record): Promise<T | null> => { const payload = await decryptPayload(key, record); return payload.type === recordType ? { id: record.id, ...(payload.data as object) } as T : null })); return values.filter(Boolean) as T[] } async listGoals(accountId: string, key: CryptoKey) { return this.list<GoalEntity>(accountId, key, 'goal') } async listEntries(accountId: string, key: CryptoKey) { return this.list<GoalEntryEntity>(accountId, key, 'goal_entry') }
  async listHistory(accountId: string, key: CryptoKey) { return this.list<GoalHistoryEntity>(accountId, key, 'goal_history') }

  /**
   * Resultado consolidado de um ano fechado. Fica guardado à parte para
   * comparação e nunca vira lançamento do ano corrente.
   */
  async saveHistory(accountId: string, key: CryptoKey, input: Omit<GoalHistoryData, 'createdAt' | 'updatedAt'>): Promise<GoalHistoryEntity> {
    if (!Number.isFinite(input.amount) || input.amount < 0) throw new Error('Informe um resultado válido.')
    if (!input.year || input.year >= new Date().getFullYear()) throw new Error('O resultado histórico é sempre de um ano já encerrado.')
    const current = (await this.listHistory(accountId, key)).find((item) => item.area === input.area && item.year === input.year)
    const now = new Date().toISOString(); const id = current?.id ?? crypto.randomUUID()
    const data: GoalHistoryData = { ...input, reference: input.reference.trim(), createdAt: current?.createdAt ?? now, updatedAt: now }
    await this.repo.saveEncrypted(accountId, currentDeviceId(accountId), id, await encryptPayload(key, { schemaVersion: 1, type: 'goal_history', data }, id), 'goal_history')
    return { id, ...data }
  }
 async saveGoal(accountId: string, key: CryptoKey, input: Omit<GoalData, 'createdAt' | 'updatedAt'>) { if (!Number.isFinite(input.target) || input.target < 0) throw new Error('Informe uma meta válida.'); const current = (await this.listGoals(accountId, key)).find((item) => item.churchId === input.churchId && item.year === input.year && item.metric === input.metric); const now = new Date().toISOString(); const id = current?.id ?? crypto.randomUUID(); const data: GoalData = { ...input, createdAt: current?.createdAt ?? now, updatedAt: now }; await this.repo.saveEncrypted(accountId, currentDeviceId(accountId), id, await encryptPayload(key, { schemaVersion: 1, type: 'goal', data }, id), 'goal'); return { id, ...data } } async addEntries(accountId: string, key: CryptoKey, entries: Array<Omit<GoalEntryData, 'createdAt' | 'source'> & { source?: GoalEntryData['source'] }>) { const now = new Date().toISOString(); for (const entry of entries) { if (!entry.churchId || !Number.isFinite(entry.amount) || entry.amount < 0) throw new Error('Revise o lançamento.'); const id = crypto.randomUUID(); const data: GoalEntryData = { ...entry, source: entry.source ?? 'manual', createdAt: now }; await this.repo.saveEncrypted(accountId, currentDeviceId(accountId), id, await encryptPayload(key, { schemaVersion: 1, type: 'goal_entry', data }, id), 'goal_entry') } } }
